/* =========================================================
   tools/chapters.cjs — the Computer Networks chapter plan.

   Source for tools/scaffold.cjs, which writes the CHAPTERS
   registry into assets/app.js and creates a placeholder page
   for every chapter that doesn't exist yet. Once a chapter is
   written, assets/app.js is the source of truth for its
   title/blurb; `cover` is only the planned outline.
   DRAFT: the course session reviews this list with the owner
   before writing chapters (docs/course-playbook.md).
   ========================================================= */
'use strict';

const P = 'Prerequisites', B = 'Beginner', I = 'Intermediate', A = 'Advanced', E = 'Expert', CS = 'Case Studies';

module.exports = [
  // ---------- Prerequisites ----------
  { n: 0.1, slug: 'p1-bytes-and-encoding', title: 'Bytes, Encoding & Byte Order', level: P, icon: '🔢', mins: 35,
    blurb: 'Bits and bytes on the wire, UTF-8, hex dumps and network byte order.',
    cover: ['Bits, bytes and octets', 'ASCII, UTF-8 and hex dumps', 'Big-endian network byte order', 'htons and friends'] },
  { n: 0.2, slug: 'p2-ip-arithmetic', title: 'IP Addresses & Binary Arithmetic', level: P, icon: '🧮', mins: 40,
    blurb: 'Dotted quads as 32-bit numbers, masks, prefixes and the arithmetic behind every subnet.',
    cover: ['An IPv4 address is a 32-bit number', 'AND with a mask', 'Prefix length', 'Private ranges'] },
  { n: 0.3, slug: 'p3-clients-servers-ports', title: 'Clients, Servers & Ports', level: P, icon: '🔌', mins: 35,
    blurb: 'Who connects to whom, what a port is, and the 5-tuple that identifies a connection.',
    cover: ['Client and server roles', 'Ports and well-known services', 'The 5-tuple', 'Listening vs connected sockets'] },
  { n: 0.4, slug: 'p4-network-cli-tools', title: 'ping, curl, dig & Friends', level: P, icon: '🧰', mins: 35,
    blurb: 'The command-line tools used throughout the course: ping, traceroute, curl, dig, ss and ip.',
    cover: ['ping and traceroute', 'curl -v', 'dig', 'ss and ip', 'Reading their output'] },
  { n: 0.5, slug: 'p5-python-sockets', title: 'Sockets in Python', level: P, icon: '🐍', mins: 45,
    blurb: 'A TCP echo server and client in a few lines, and what each socket call does.',
    cover: ['socket, bind, listen, accept', 'connect, send, recv', 'An echo server', 'UDP sockets', 'Blocking and timeouts'] },
  { n: 0.6, slug: 'p6-wireshark-basics', title: 'Reading Packets with Wireshark', level: P, icon: '🦈', mins: 40,
    blurb: 'Capturing traffic, filters, and reading one packet layer by layer.',
    cover: ['Capture vs display filters', 'The packet list and details panes', 'Following a TCP stream', 'tcpdump for servers'] },
  { n: 0.7, slug: 'p7-layering', title: 'Layering & Encapsulation', level: P, icon: '🧅', mins: 35,
    blurb: 'Why networks are built in layers, and how each layer wraps the one above in its own header.',
    cover: ['Headers and payloads', 'Encapsulation down the stack', 'What each layer is responsible for', 'Why layering works (and where it leaks)'] },
  { n: 0.8, slug: 'p8-latency-bandwidth', title: 'Latency, Bandwidth & Throughput', level: P, icon: '⏱️', mins: 35,
    blurb: 'Propagation vs transmission delay, bandwidth-delay product, and why "fast internet" can still feel slow.',
    cover: ['Propagation, transmission, queuing delay', 'Bandwidth vs latency', 'Round-trip time', 'Bandwidth-delay product'] },

  // ---------- Beginner ----------
  { n: 1, slug: '01-osi-vs-tcp-ip', title: 'OSI vs TCP/IP', level: B, icon: '🗂️', mins: 35,
    blurb: 'The seven-layer model interviewers ask about, the four-layer model the internet uses, and how they map.',
    cover: ['The seven OSI layers', 'The TCP/IP stack', 'Mapping one to the other', 'What a networking interview asks'] },
  { n: 2, slug: '02-ethernet-switches', title: 'Ethernet, MAC Addresses & Switches', level: B, icon: '🔀', mins: 40,
    blurb: 'Frames and MAC addresses, how a switch learns where hosts are, and broadcast domains.',
    cover: ['Ethernet frames', 'MAC addresses', 'MAC learning tables', 'Broadcast and flooding', 'Hubs vs switches vs routers'] },
  { n: 3, slug: '03-arp', title: 'ARP: From IP to MAC', level: B, icon: '📣', mins: 35,
    blurb: 'How a host finds the MAC for an IP on its LAN, ARP caches, and ARP spoofing.',
    cover: ['Who has 10.0.0.5?', 'The ARP cache', 'Gratuitous ARP', 'ARP spoofing'] },
  { n: 4, slug: '04-ip-subnetting', title: 'IP Addressing & Subnetting', level: B, icon: '🧩', mins: 50,
    blurb: 'CIDR, subnet masks and splitting a network by hand, with a subnet calculator you can drive.',
    cover: ['CIDR notation', 'Network and broadcast addresses', 'Splitting a /24', 'Supernetting', 'Private addressing'] },
  { n: 5, slug: '05-routing-tables', title: 'Routing Tables & Forwarding', level: B, icon: '🧭', mins: 45,
    blurb: 'Longest-prefix match, default routes, and how a packet crosses routers hop by hop.',
    cover: ['The routing table', 'Longest-prefix match', 'Default gateway', 'Hop-by-hop forwarding', 'TTL'] },
  { n: 6, slug: '06-icmp-traceroute', title: 'ICMP, ping & traceroute', level: B, icon: '📍', mins: 35,
    blurb: 'Echo requests, time-exceeded messages, and how traceroute exploits TTL to map a path.',
    cover: ['ICMP message types', 'How ping works', 'How traceroute works', 'Path MTU discovery'] },
  { n: 7, slug: '07-udp', title: 'UDP', level: B, icon: '📦', mins: 35,
    blurb: 'Datagrams without connections: the 8-byte header, and when unreliable is the right choice.',
    cover: ['The UDP header', 'No connection, no order, no retransmit', 'Where UDP wins: DNS, games, video', 'Building reliability on top'] },
  { n: 8, slug: '08-tcp-handshake', title: 'TCP: The Handshake & the Byte Stream', level: B, icon: '🤝', mins: 50,
    blurb: 'SYN, SYN-ACK, ACK; sequence numbers; and why TCP is a byte stream, not messages.',
    cover: ['The three-way handshake', 'Sequence and acknowledgement numbers', 'A byte stream, not messages', 'The TCP state machine', 'SYN floods and SYN cookies'] },
  { n: 9, slug: '09-nat-ports-sockets', title: 'NAT, Ports & Sockets', level: B, icon: '🚪', mins: 45,
    blurb: 'How many devices share one public IP, NAT tables, port exhaustion and hole punching.',
    cover: ['Why NAT exists', 'The NAT translation table', 'Port exhaustion', 'Hole punching and STUN'] },
  { n: 10, slug: '10-dns-resolution', title: 'DNS Resolution', level: B, icon: '📒', mins: 50,
    blurb: 'Stub, recursive and authoritative servers, a lookup traced from the root, and caching with TTLs.',
    cover: ['Names, zones and records', 'Recursive vs iterative queries', 'A lookup from the root', 'Caching and TTLs', 'dig +trace'] },

  // ---------- Intermediate ----------
  { n: 11, slug: '11-tcp-reliability', title: 'TCP Reliability: ACKs & Retransmission', level: I, icon: '🔁', mins: 45,
    blurb: 'Timeouts, cumulative and selective ACKs, fast retransmit, and how TCP estimates RTT.',
    cover: ['Retransmission timeout', 'RTT estimation', 'Cumulative ACKs and SACK', 'Fast retransmit', 'Duplicate ACKs'] },
  { n: 12, slug: '12-flow-control', title: 'Flow Control & the Receive Window', level: I, icon: '🚰', mins: 40,
    blurb: 'How a slow receiver stops a fast sender: the receive window, zero windows and window scaling.',
    cover: ['The receive window', 'Zero window and probes', 'Window scaling', 'Sliding windows visualised'] },
  { n: 13, slug: '13-congestion-control', title: 'Congestion Control: Slow Start, CUBIC & BBR', level: I, icon: '🚦', mins: 55,
    blurb: 'How TCP discovers the network\'s capacity: slow start, AIMD, CUBIC and BBR, with a cwnd simulator.',
    cover: ['Why congestion control', 'Slow start and congestion avoidance', 'AIMD and the sawtooth', 'CUBIC', 'BBR'] },
  { n: 14, slug: '14-tcp-teardown-time-wait', title: 'Closing Connections & TIME_WAIT', level: I, icon: '👋', mins: 40,
    blurb: 'FIN and RST, the four-way close, and why TIME_WAIT exists and bites busy servers.',
    cover: ['FIN, ACK, FIN, ACK', 'Half-closed connections', 'RST', 'TIME_WAIT and 2×MSL', 'SO_REUSEADDR'] },
  { n: 15, slug: '15-http-1-1', title: 'HTTP/1.1', level: I, icon: '📄', mins: 45,
    blurb: 'Requests, responses, headers and status codes; keep-alive, pipelining and head-of-line blocking.',
    cover: ['Anatomy of a request and response', 'Methods and status codes', 'Keep-alive', 'Pipelining and its failure', 'Caching headers'] },
  { n: 16, slug: '16-http-2', title: 'HTTP/2', level: I, icon: '🧵', mins: 45,
    blurb: 'Binary framing, streams multiplexed on one connection, HPACK, and TCP head-of-line blocking.',
    cover: ['Frames and streams', 'Multiplexing', 'HPACK header compression', 'Server push (and its retirement)', 'TCP head-of-line blocking'] },
  { n: 17, slug: '17-tls-1-3', title: 'TLS 1.3 & Certificates', level: I, icon: '🔐', mins: 55,
    blurb: 'The 1-RTT handshake, key exchange, certificate chains and how a browser decides to trust a site.',
    cover: ['What TLS guarantees', 'The TLS 1.3 handshake', 'ECDHE key exchange', 'Certificate chains and CAs', '0-RTT resumption and its risk'] },
  { n: 18, slug: '18-http-3-quic', title: 'HTTP/3 & QUIC', level: I, icon: '⚡', mins: 45,
    blurb: 'Transport over UDP: streams without head-of-line blocking, 0-RTT, and connection migration.',
    cover: ['Why QUIC runs on UDP', 'Independent streams', 'Built-in TLS', '0-RTT', 'Connection IDs and migration'] },
  { n: 19, slug: '19-dhcp', title: 'DHCP', level: I, icon: '🏷️', mins: 30,
    blurb: 'How a device gets an address when it joins a network: discover, offer, request, acknowledge.',
    cover: ['DORA', 'Leases and renewal', 'Relays', 'Rogue DHCP servers'] },
  { n: 20, slug: '20-ipv6', title: 'IPv6', level: I, icon: '6️⃣', mins: 40,
    blurb: '128-bit addresses, SLAAC, no broadcast, and running IPv4 and IPv6 side by side.',
    cover: ['Address format and shortening', 'SLAAC and neighbour discovery', 'No NAT, no broadcast', 'Dual stack and Happy Eyeballs'] },
  { n: 21, slug: '21-websockets-sse', title: 'WebSockets & Server-Sent Events', level: I, icon: '📡', mins: 40,
    blurb: 'Keeping a connection open for push: the WebSocket upgrade, frames, SSE, and long polling.',
    cover: ['Polling and long polling', 'The WebSocket upgrade', 'Frames and ping/pong', 'Server-Sent Events', 'Scaling many open connections'] },
  { n: 22, slug: '22-grpc-on-the-wire', title: 'REST & gRPC on the Wire', level: I, icon: '📞', mins: 45,
    blurb: 'What JSON over HTTP/1.1 and Protobuf over HTTP/2 actually look like in a packet capture.',
    cover: ['REST request on the wire', 'Protobuf encoding', 'gRPC over HTTP/2 frames', 'Streaming RPCs', 'Deadlines'] },
  { n: 23, slug: '23-proxies', title: 'Forward & Reverse Proxies', level: I, icon: '🪞', mins: 40,
    blurb: 'What sits between client and server: forward proxies, reverse proxies, TLS termination and headers.',
    cover: ['Forward vs reverse', 'TLS termination', 'X-Forwarded-For and PROXY protocol', 'Connection pooling to backends'] },
  { n: 24, slug: '24-load-balancers-l4-l7', title: 'Load Balancers: L4 vs L7', level: I, icon: '⚖️', mins: 50,
    blurb: 'Balancing by connection vs by request, algorithms, health checks and sticky sessions.',
    cover: ['L4: packets and connections', 'L7: HTTP-aware routing', 'Algorithms: round robin, least connections, hashing', 'Health checks', 'Direct server return'] },

  // ---------- Advanced ----------
  { n: 25, slug: '25-bgp', title: 'BGP: How the Internet Routes', level: A, icon: '🌍', mins: 55,
    blurb: 'Autonomous systems, route announcements, path selection and how a mistake takes a company offline.',
    cover: ['Autonomous systems', 'Announcements and withdrawals', 'Path selection', 'Route leaks and hijacks', 'RPKI'] },
  { n: 26, slug: '26-anycast-cdn', title: 'Anycast & CDNs', level: A, icon: '🛰️', mins: 45,
    blurb: 'One IP announced from many places, edge caching, and how a CDN picks your nearest server.',
    cover: ['Anycast routing', 'Edge caches and cache keys', 'Request routing: DNS vs anycast', 'Origin shielding'] },
  { n: 27, slug: '27-dns-in-depth', title: 'DNS in Depth: DNSSEC, GeoDNS & Failover', level: A, icon: '🧭', mins: 45,
    blurb: 'Signed zones, geographic answers, low TTLs for failover, and DNS over HTTPS.',
    cover: ['DNSSEC chain of trust', 'GeoDNS and latency routing', 'Failover and TTL trade-offs', 'DoH and DoT'] },
  { n: 28, slug: '28-vpns-tunnels', title: 'VPNs & Tunnels: IPsec, WireGuard', level: A, icon: '🚇', mins: 45,
    blurb: 'Encapsulating packets inside packets, IPsec modes, and WireGuard\'s minimal design.',
    cover: ['Tunnelling and encapsulation', 'IPsec transport vs tunnel mode', 'WireGuard', 'MTU problems in tunnels'] },
  { n: 29, slug: '29-vlans-vxlan', title: 'VLANs & Overlay Networks (VXLAN)', level: A, icon: '🧱', mins: 40,
    blurb: 'Splitting one physical network into many, and building virtual L2 networks over L3.',
    cover: ['802.1Q tags', 'Trunks', 'VXLAN encapsulation', 'Why clouds use overlays'] },
  { n: 30, slug: '30-data-center-networks', title: 'Data-Centre Networks: Clos & Leaf–Spine', level: A, icon: '🏢', mins: 45,
    blurb: 'Why data centres use leaf–spine fabrics, ECMP, and east–west traffic.',
    cover: ['Three-tier vs leaf–spine', 'Clos networks', 'ECMP', 'Oversubscription', 'East–west traffic'] },
  { n: 31, slug: '31-kubernetes-networking', title: 'Kubernetes Networking & CNI', level: A, icon: '☸️', mins: 50,
    blurb: 'Pod IPs, Services and kube-proxy, CNI plugins, and how a packet reaches a pod.',
    cover: ['Every pod gets an IP', 'Services and kube-proxy (iptables/IPVS)', 'CNI plugins', 'Ingress', 'Network policies'] },
  { n: 32, slug: '32-service-mesh-mtls', title: 'Service Mesh & mTLS', level: A, icon: '🕸️', mins: 45,
    blurb: 'Sidecar proxies, mutual TLS between services, and what a mesh buys and costs.',
    cover: ['Sidecars and Envoy', 'mTLS and workload identity', 'Retries and timeouts in the mesh', 'Sidecarless (ambient) meshes'] },
  { n: 33, slug: '33-tcp-performance', title: 'TCP Performance: Nagle, Delayed ACK & HOL', level: A, icon: '🐌', mins: 45,
    blurb: 'The small-packet traps that add 40 ms, buffer sizing, and head-of-line blocking.',
    cover: ['Nagle\'s algorithm', 'Delayed ACKs and the 40 ms stall', 'TCP_NODELAY', 'Buffer sizing and BDP', 'Head-of-line blocking'] },
  { n: 34, slug: '34-kernel-networking', title: 'Kernel Networking: NICs, Interrupts & Zero-Copy', level: A, icon: '🧬', mins: 50,
    blurb: 'From wire to socket: NIC queues, interrupts and NAPI, sendfile, and kernel bypass with DPDK.',
    cover: ['NIC ring buffers and RSS', 'Interrupts and NAPI polling', 'The socket buffer', 'sendfile and zero-copy', 'DPDK and XDP'] },
  { n: 35, slug: '35-firewalls-iptables', title: 'Firewalls, iptables & Security Groups', level: A, icon: '🧱', mins: 45,
    blurb: 'Stateful filtering, netfilter chains, conntrack, and cloud security groups.',
    cover: ['Stateless vs stateful', 'netfilter and iptables chains', 'conntrack', 'nftables', 'Security groups and NACLs'] },
  { n: 36, slug: '36-ddos-network-security', title: 'DDoS & Network Attacks', level: A, icon: '🌪️', mins: 45,
    blurb: 'Volumetric, protocol and application-layer attacks, amplification, and how mitigation works.',
    cover: ['Volumetric floods', 'Amplification (DNS, NTP, memcached)', 'SYN floods', 'Layer-7 attacks', 'Scrubbing and rate limiting'] },

  // ---------- Expert ----------
  { n: 37, slug: '37-packet-level-debugging', title: 'Packet-Level Debugging', level: E, icon: '🔬', mins: 45,
    blurb: 'Reading tcpdump output to find retransmits, resets, zero windows and slow handshakes.',
    cover: ['A debugging checklist', 'Spotting retransmissions', 'Resets and who sent them', 'Measuring RTT from a capture'] },
  { n: 38, slug: '38-latency-budgets', title: 'Internet Latency Budgets', level: E, icon: '📏', mins: 40,
    blurb: 'Where the milliseconds go in a page load, round trips you can remove, and the speed of light.',
    cover: ['DNS, TCP, TLS, request: the round trips', 'Speed of light in fibre', 'Connection reuse and preconnect', 'Measuring with curl -w'] },
  { n: 39, slug: '39-sdn', title: 'Software-Defined Networking', level: E, icon: '🎛️', mins: 40,
    blurb: 'Separating control and data planes, OpenFlow, and programmable switches.',
    cover: ['Control plane vs data plane', 'OpenFlow', 'SDN in clouds', 'P4 and programmable data planes'] },
  { n: 40, slug: '40-networking-interview-playbook', title: 'Networking Interview Playbook', level: E, icon: '🎤', mins: 40,
    blurb: 'The questions that come up, the "what happens when you type a URL" answer done properly, and the traps.',
    cover: ['Question map by layer', 'The URL question, layer by layer', 'TCP vs UDP done well', 'Troubleshooting questions', 'Trick questions'] },

  // ---------- Case studies ----------
  { n: 41, slug: '41-case-typing-a-url', title: 'Case Study: Typing google.com, Packet by Packet', level: CS, icon: '⌨️', mins: 50,
    blurb: 'DNS, ARP, TCP, TLS and HTTP/2 traced in order, with the packets you would see.',
    cover: ['DNS lookup', 'ARP for the gateway', 'TCP and TLS handshakes', 'HTTP/2 request', 'Rendering starts'] },
  { n: 42, slug: '42-case-webrtc-call', title: 'Case Study: A WebRTC Video Call', level: CS, icon: '📹', mins: 45,
    blurb: 'Signalling, ICE, STUN and TURN through NATs, and media over SRTP/UDP.',
    cover: ['Signalling', 'ICE candidates', 'STUN and TURN', 'SRTP and jitter buffers'] },
  { n: 43, slug: '43-case-cdn-viral-video', title: 'Case Study: A CDN Serves a Viral Video', level: CS, icon: '🎬', mins: 45,
    blurb: 'A million viewers in an hour: edge caching, origin shielding, cache stampedes and adaptive bitrate.',
    cover: ['The traffic spike', 'Cache hits and misses at the edge', 'Stampede protection', 'Adaptive bitrate streaming'] },
  { n: 44, slug: '44-case-facebook-bgp-outage', title: 'Case Study: Facebook\'s 2021 BGP Outage', level: CS, icon: '📴', mins: 40,
    blurb: 'A maintenance command withdrew the routes, DNS went with them, and engineers couldn\'t get in.',
    cover: ['The command', 'Routes withdrawn', 'DNS servers pull themselves', 'Locked out', 'Lessons'] },
  { n: 45, slug: '45-case-dyn-dns-attack', title: 'Case Study: The 2016 Dyn DNS Attack', level: CS, icon: '🧟', mins: 40,
    blurb: 'The Mirai botnet flooded a DNS provider and took half the web\'s names with it.',
    cover: ['Mirai and IoT botnets', 'The attack on Dyn', 'Why sites went down', 'Secondary DNS and resilience'] },
  { n: 46, slug: '46-case-lb-failover', title: 'Case Study: Load-Balancer Failover', level: CS, icon: '🔀', mins: 40,
    blurb: 'A backend dies mid-traffic: health checks, connection draining and what users actually see.',
    cover: ['Health-check timing', 'Draining connections', 'Retries and idempotency', 'Active–passive LB pairs and VRRP'] },
  { n: 47, slug: '47-case-udp-games', title: 'Case Study: Networking for Multiplayer Games', level: CS, icon: '🎮', mins: 40,
    blurb: 'Why games use UDP, client-side prediction, lag compensation and tick rates.',
    cover: ['Why not TCP', 'Tick rate and snapshots', 'Client-side prediction', 'Lag compensation', 'Reliable-over-UDP'] },
  { n: 48, slug: '48-case-slow-api', title: 'Case Study: Debugging a Slow API from a Capture', level: CS, icon: '🐢', mins: 45,
    blurb: 'A p99 of 2 seconds traced to a delayed-ACK interaction, a small window and a missing keep-alive.',
    cover: ['The symptom', 'The capture', 'Finding the 200 ms gaps', 'The fixes', 'Verifying'] },
];

module.exports.levels = {
  Prerequisites: 'Bytes, addresses, sockets and the tools the course uses, taught from zero.',
  Beginner: 'How a packet gets from one host to another: Ethernet, IP, routing, UDP, TCP and DNS.',
  Intermediate: 'TCP in depth, HTTP/1.1 to HTTP/3, TLS, proxies and load balancers.',
  Advanced: 'The internet and the data centre: BGP, CDNs, overlays, Kubernetes networking, kernel networking and security.',
  Expert: 'Packet-level debugging, latency budgets, SDN and the interview playbook.',
  'Case Studies': 'Eight real traces and outages, from typing a URL to Facebook\'s BGP outage.',
};
