/* ---------------------------------------------------------------------------
   Practice-item → resource map.

   Each entry is [needle, target]:
     needle  lowercase phrase matched against the practice item's text
     target  a LeetCode slug, or a full https:// URL (cp-algorithms etc.)

   Matching is longest-needle-first over non-overlapping spans, so an item
   mentioning several problems gets several links, and "single number ii"
   wins over "single number" because it claims the longer span.

   Every LeetCode slug here is validated against the live problem list by
   tools/lc-links.js, so a typo fails loudly instead of shipping a dead link.
   --------------------------------------------------------------------------- */

const CP = 'https://cp-algorithms.com/';

module.exports = [
  /* ---- arrays, two pointers ---- */
  ['remove element', 'remove-element'],
  ['move zeroes', 'move-zeroes'],
  ['move all zeroes', 'move-zeroes'],
  ['remove duplicates, allowing two copies', 'remove-duplicates-from-sorted-array-ii'],
  ['remove duplicates from a sorted array allowing at most two', 'remove-duplicates-from-sorted-array-ii'],
  ['remove duplicates from a sorted array', 'remove-duplicates-from-sorted-array'],
  ['rotate an array right by k', 'rotate-array'],
  ['rotate an n×n matrix', 'rotate-image'],
  ['set every row and column containing a zero', 'set-matrix-zeroes'],
  ['first missing positive', 'first-missing-positive'],
  ['two sum on a sorted array', 'two-sum-ii-input-array-is-sorted'],
  ['valid palindrome', 'valid-palindrome'],
  ['middle of a linked list', 'middle-of-the-linked-list'],
  ['middle of the list', 'middle-of-the-linked-list'],
  ['3-sum', '3sum'],
  ['container with most water', 'container-with-most-water'],
  ['sort colours', 'sort-colors'],
  ['find the duplicate number', 'find-the-duplicate-number'],
  ['4-sum', '4sum'],
  ['trapping rain water', 'trapping-rain-water'],

  /* ---- sliding window ---- */
  ['maximum average subarray', 'maximum-average-subarray-i'],
  ['contains a duplicate within distance k', 'contains-duplicate-ii'],
  ['contains duplicate within distance k', 'contains-duplicate-ii'],
  ['longest substring without repeating characters', 'longest-substring-without-repeating-characters'],
  ['longest repeating character replacement', 'longest-repeating-character-replacement'],
  ['minimum size subarray', 'minimum-size-subarray-sum'],
  ['permutation in string', 'permutation-in-string'],
  ['find all anagrams', 'find-all-anagrams-in-a-string'],
  ['fruit into baskets', 'fruit-into-baskets'],
  ['longest substring with at most k distinct', 'longest-substring-with-at-most-k-distinct-characters'],
  ['minimum window substring', 'minimum-window-substring'],
  ['subarrays with exactly k distinct', 'subarrays-with-k-different-integers'],
  ['shortest subarray with sum ≥ k', 'shortest-subarray-with-sum-at-least-k'],

  /* ---- prefix sums ---- */
  ['range sum query — immutable', 'range-sum-query-immutable'],
  ['range sum query 2d — immutable', 'range-sum-query-2d-immutable'],
  ['range sum query 2d — mutable', 'range-sum-query-2d-mutable'],
  ['range sum query — mutable', 'range-sum-query-mutable'],
  ['pivot / equilibrium index', 'find-pivot-index'],
  ['running sum of an array', 'running-sum-of-1d-array'],
  ['subarray sum equals k', 'subarray-sum-equals-k'],
  ['subarray sums divisible by k', 'subarray-sums-divisible-by-k'],
  ['contiguous array', 'contiguous-array'],
  ['product of array except self', 'product-of-array-except-self'],
  ['car pooling', 'car-pooling'],
  ['corporate flight bookings', 'corporate-flight-bookings'],
  ['maximum sum rectangle in a 2d matrix', 'max-sum-of-rectangle-no-larger-than-k'],
  ['count subarrays with xor equal to k', 'https://www.geeksforgeeks.org/count-number-subarrays-given-xor/'],

  /* ---- binary search ---- */
  ['binary search;', 'binary-search'],
  ['search-insert-position', 'search-insert-position'],
  ['integer square root', 'sqrtx'],
  ['first bad version', 'first-bad-version'],
  ['find first and last position', 'find-first-and-last-position-of-element-in-sorted-array'],
  ['search in a rotated sorted array, then the version with duplicates', 'search-in-rotated-sorted-array-ii'],
  ['search in a rotated sorted array', 'search-in-rotated-sorted-array'],
  ['find the peak element', 'find-peak-element'],
  ['koko eating bananas', 'koko-eating-bananas'],
  ['capacity to ship packages', 'capacity-to-ship-packages-within-d-days'],
  ['minimum days to make m bouquets', 'minimum-number-of-days-to-make-m-bouquets'],
  ['minimum days to ship all packages', 'capacity-to-ship-packages-within-d-days'],
  ['kth smallest element in a sorted matrix', 'kth-smallest-element-in-a-sorted-matrix'],
  ['split array to minimise the largest sum', 'split-array-largest-sum'],
  ['median of two sorted arrays', 'median-of-two-sorted-arrays'],
  ['magnetic force between balls', 'magnetic-force-between-two-balls'],
  ['aggressive cows', 'magnetic-force-between-two-balls'],

  /* ---- sorting ---- */
  ['merge two sorted arrays in place', 'merge-sorted-array'],
  ['dutch national flag', 'sort-colors'],
  ['sort an array by frequency', 'sort-array-by-increasing-frequency'],
  ['merge intervals', 'merge-intervals'],
  ['insert one interval', 'insert-interval'],
  ['insert interval', 'insert-interval'],
  ['largest number formable by concatenating', 'largest-number'],
  ['kth largest element', 'kth-largest-element-in-an-array'],
  ['k-th largest element', 'kth-largest-element-in-an-array'],
  ['sort a linked list', 'sort-list'],
  ['sort a list in o(n log n)', 'sort-list'],
  ['count inversions', 'reverse-pairs'],
  ['reverse pairs', 'reverse-pairs'],
  ['count of smaller numbers after self', 'count-of-smaller-numbers-after-self'],
  ['maximum gap', 'maximum-gap'],

  /* ---- hashing ---- */
  ['two sum (unsorted', 'two-sum'],
  ['contains duplicate;', 'contains-duplicate'],
  ['valid anagram', 'valid-anagram'],
  ['intersection of two arrays', 'intersection-of-two-arrays'],
  ['group anagrams', 'group-anagrams'],
  ['top k frequent elements', 'top-k-frequent-elements'],
  ['top k frequent words', 'top-k-frequent-words'],
  ['longest consecutive sequence', 'longest-consecutive-sequence'],
  ['isomorphic strings', 'isomorphic-strings'],
  ['word pattern', 'word-pattern'],
  ['insert, delete and getrandom in o(1)', 'insert-delete-getrandom-o1'],
  ['insert/delete/getrandom in o(1), then the duplicates-allowed', 'insert-delete-getrandom-o1-duplicates-allowed'],
  ['insert/delete/getrandom in o(1)', 'insert-delete-getrandom-o1'],
  ['substring with concatenation of all words', 'substring-with-concatenation-of-all-words'],
  ['maximum points on a line', 'max-points-on-a-line'],

  /* ---- strings ---- */
  ['ransom note', 'ransom-note'],
  ['reverse a string, then reverse only the vowels', 'reverse-vowels-of-a-string'],
  ['longest common prefix', 'longest-common-prefix'],
  ['first unique character in a string', 'first-unique-character-in-a-string'],
  ['longest palindromic substring', 'longest-palindromic-substring'],
  ['string compression', 'string-compression'],
  ['reverse words in a string', 'reverse-words-in-a-string'],
  ['zigzag conversion', 'zigzag-conversion'],
  ['string-to-integer (atoi)', 'string-to-integer-atoi'],
  ['valid number', 'valid-number'],

  /* ---- recursion ---- */
  ['power(a,b)', 'powx-n'],
  ['pow(x, n)', 'powx-n'],
  ['reverse a linked list', 'reverse-linked-list'],
  ['reverse a string recursively', 'reverse-string'],
  ['fibonacci with memoisation', 'fibonacci-number'],
  ['fibonacci three ways', 'fibonacci-number'],
  ['all subsets of an array; then all subsets when duplicates', 'subsets-ii'],
  ['all subsets of an array', 'subsets'],
  ['subsets and subsets ii', 'subsets-ii'],
  ['subsets; subsets ii', 'subsets-ii'],
  ['generate all balanced parentheses', 'generate-parentheses'],
  ['generate parentheses', 'generate-parentheses'],
  ['all valid parenthesisations', 'generate-parentheses'],
  ['tower of hanoi', 'https://www.geeksforgeeks.org/c-program-for-tower-of-hanoi/'],
  ['iterative inorder, preorder and postorder', 'binary-tree-inorder-traversal'],
  ['flatten a nested list iterator', 'flatten-nested-list-iterator'],
  ['permutations of a string with duplicates', 'permutations-ii'],
  ['permutations; permutations ii', 'permutations-ii'],
  ['sort a stack using only recursion', 'https://www.geeksforgeeks.org/sort-a-stack-using-recursion/'],

  /* ---- linked lists ---- */
  ['merge two sorted lists', 'merge-two-sorted-lists'],
  ['remove all nodes with a given value', 'remove-linked-list-elements'],
  ['remove duplicates from a sorted list; then remove all nodes that have duplicates', 'remove-duplicates-from-sorted-list-ii'],
  ['remove duplicates from a sorted list', 'remove-duplicates-from-sorted-list'],
  ['remove the nth node from the end', 'remove-nth-node-from-end-of-list'],
  ['add two numbers represented as reversed lists', 'add-two-numbers'],
  ['detect a cycle and return its entry node', 'linked-list-cycle-ii'],
  ['reverse a sublist from position left to right', 'reverse-linked-list-ii'],
  ['reorder the list', 'reorder-list'],
  ['odd-even linked list', 'odd-even-linked-list'],
  ['swap nodes in pairs', 'swap-nodes-in-pairs'],
  ['copy a list with random pointers', 'copy-list-with-random-pointer'],
  ['reverse nodes in k-groups', 'reverse-nodes-in-k-group'],
  ['merge k sorted lists', 'merge-k-sorted-lists'],
  ['flatten a multilevel doubly linked list', 'flatten-a-multilevel-doubly-linked-list'],

  /* ---- stacks ---- */
  ['valid parentheses', 'valid-parentheses'],
  ['min stack', 'min-stack'],
  ['min-stack', 'min-stack'],
  ['max-stack', 'max-stack'],
  ['backspace string compare', 'backspace-string-compare'],
  ['remove all adjacent duplicates', 'remove-all-adjacent-duplicates-in-string'],
  ['evaluate reverse polish notation', 'evaluate-reverse-polish-notation'],
  ['next greater element i', 'next-greater-element-i'],
  ['next greater element ii', 'next-greater-element-ii'],
  ['daily temperatures', 'daily-temperatures'],
  ['days until a warmer temperature', 'daily-temperatures'],
  ['online stock span', 'online-stock-span'],
  ['asteroid collision', 'asteroid-collision'],
  ['car fleet', 'car-fleet'],
  ['decode string', 'decode-string'],
  ['simplify a unix path', 'simplify-path'],
  ['remove k digits', 'remove-k-digits'],
  ['implement a queue using two stacks', 'implement-queue-using-stacks'],
  ['implement a queue using stacks', 'implement-queue-using-stacks'],
  ['queue from two stacks', 'implement-queue-using-stacks'],
  ['stack using queues', 'implement-stack-using-queues'],
  ['stack from two queues', 'implement-stack-using-queues'],
  ['largest rectangle in a histogram', 'largest-rectangle-in-histogram'],
  ['maximal rectangle', 'maximal-rectangle'],
  ['sum of subarray minimums', 'sum-of-subarray-minimums'],
  ['basic calculator', 'basic-calculator'],

  /* ---- queues, deques ---- */
  ['design a circular queue, then a circular deque', 'design-circular-deque'],
  ['design a circular queue', 'design-circular-queue'],
  ['number of recent calls', 'number-of-recent-calls'],
  ['moving average from a data stream', 'moving-average-from-data-stream'],
  ['first unique character in a stream', 'first-unique-character-in-a-string'],
  ['continuous subarray sum', 'continuous-subarray-sum'],
  ['longest continuous subarray with absolute diff', 'longest-continuous-subarray-with-absolute-diff-less-than-or-equal-to-limit'],
  ['longest subarray with max − min ≤ k', 'longest-continuous-subarray-with-absolute-diff-less-than-or-equal-to-limit'],
  ['sliding window maximum', 'sliding-window-maximum'],
  ['jump game vi', 'jump-game-vi'],
  ['constrained subsequence sum', 'constrained-subsequence-sum'],
  ['shortest path in a binary matrix', 'shortest-path-in-binary-matrix'],

  /* ---- heaps ---- */
  ['last stone weight ii', 'last-stone-weight-ii'],
  ['last stone weight', 'last-stone-weight'],
  ['k weakest rows', 'the-k-weakest-rows-in-a-matrix'],
  ['k closest points to the origin', 'k-closest-points-to-origin'],
  ['kth largest element in a stream', 'kth-largest-element-in-a-stream'],
  ['reorganize string', 'reorganize-string'],
  ['task scheduler', 'task-scheduler'],
  ['minimum cost to connect sticks', 'minimum-cost-to-connect-sticks'],
  ['meeting rooms ii', 'meeting-rooms-ii'],
  ['minimum meeting rooms', 'meeting-rooms-ii'],
  ['find the median from a data stream', 'find-median-from-data-stream'],
  ['find median from a data stream', 'find-median-from-data-stream'],
  ['median of a stream', 'find-median-from-data-stream'],
  ['sliding window median', 'sliding-window-median'],
  ['sliding-window median', 'sliding-window-median'],
  ['smallest range covering elements from k lists', 'smallest-range-covering-elements-from-k-lists'],
  ['ipo', 'ipo'],

  /* ---- binary trees ---- */
  ['maximum depth of a binary tree', 'maximum-depth-of-binary-tree'],
  ['maximum depth;', 'maximum-depth-of-binary-tree'],
  ['count total nodes', 'count-complete-tree-nodes'],
  ['invert a binary tree', 'invert-binary-tree'],
  ['invert a tree', 'invert-binary-tree'],
  ['check if two trees are identical', 'same-tree'],
  ['check if two trees are the same', 'same-tree'],
  ['sum of all left leaves', 'sum-of-left-leaves'],
  ['morris inorder traversal', 'binary-tree-inorder-traversal'],
  ['flatten a binary tree to a linked list', 'flatten-binary-tree-to-linked-list'],
  ['binary tree paths', 'binary-tree-paths'],
  ['count good nodes', 'count-good-nodes-in-binary-tree'],
  ['construct a tree from preorder + inorder', 'construct-binary-tree-from-preorder-and-inorder-traversal'],
  ['from inorder + postorder', 'construct-binary-tree-from-inorder-and-postorder-traversal'],
  ['iterative postorder in a single pass', 'binary-tree-postorder-traversal'],
  ['binary tree cameras', 'binary-tree-cameras'],
  ['level order traversal; then bottom-up level order', 'binary-tree-level-order-traversal-ii'],
  ['level order traversal', 'binary-tree-level-order-traversal'],
  ['average of levels', 'average-of-levels-in-binary-tree'],
  ['largest value in each level', 'find-largest-value-in-each-tree-row'],
  ['minimum depth of a binary tree', 'minimum-depth-of-binary-tree'],
  ['zigzag level order traversal', 'binary-tree-zigzag-level-order-traversal'],
  ['right view, then left view', 'binary-tree-right-side-view'],
  ['top view and bottom view', 'https://www.geeksforgeeks.org/print-nodes-top-view-binary-tree/'],
  ['populate next-right pointers', 'populating-next-right-pointers-in-each-node-ii'],
  ['maximum width of a binary tree', 'maximum-width-of-binary-tree'],
  ['deepest leftmost value', 'find-bottom-left-tree-value'],
  ['all nodes at distance k', 'all-nodes-distance-k-in-binary-tree'],
  ['find all nodes at distance k', 'all-nodes-distance-k-in-binary-tree'],
  ['vertical order traversal', 'vertical-order-traversal-of-a-binary-tree'],
  ['boundary traversal', 'https://www.geeksforgeeks.org/boundary-traversal-of-binary-tree/'],
  ['serialize and deserialize a binary tree', 'serialize-and-deserialize-binary-tree'],

  /* ---- tree problems ---- */
  ['path sum — does any root-to-leaf', 'path-sum'],
  ['path sum iii', 'path-sum-iii'],
  ['balanced binary tree', 'balanced-binary-tree'],
  ['subtree of another tree', 'subtree-of-another-tree'],
  ['symmetric tree', 'symmetric-tree'],
  ['diameter of a binary tree', 'diameter-of-binary-tree'],
  ['sum of root-to-leaf numbers', 'sum-root-to-leaf-numbers'],
  ['lowest common ancestor in a binary tree', 'lowest-common-ancestor-of-a-binary-tree'],
  ['lowest common ancestor in a bst', 'lowest-common-ancestor-of-a-binary-search-tree'],
  ['count univalue subtrees', 'count-univalue-subtrees'],
  ['longest univalue path', 'longest-univalue-path'],
  ['binary tree maximum path sum', 'binary-tree-maximum-path-sum'],
  ['lca with binary lifting', CP + 'graph/lca_binary_lifting.html'],
  ['k-th ancestor of a node', 'kth-ancestor-of-a-tree-node'],
  ['distribute coins in a binary tree', 'distribute-coins-in-binary-tree'],
  ['burn a tree from a target node', 'amount-of-time-for-binary-tree-to-be-infected'],
  ['largest bst subtree', 'largest-bst-subtree'],
  ['house robber iii', 'house-robber-iii'],
  ['sum of distances in a tree', 'sum-of-distances-in-tree'],
  ['minimum height trees', 'minimum-height-trees'],

  /* ---- BST ---- */
  ['search in a bst', 'search-in-a-binary-search-tree'],
  ['insert into a bst', 'insert-into-a-binary-search-tree'],
  ['minimum absolute difference in a bst', 'minimum-absolute-difference-in-bst'],
  ['range sum of a bst', 'range-sum-of-bst'],
  ['convert a sorted array to a height-balanced bst', 'convert-sorted-array-to-binary-search-tree'],
  ['validate a bst', 'validate-binary-search-tree'],
  ['kth smallest element in a bst', 'kth-smallest-element-in-a-bst'],
  ['kth smallest in a bst', 'kth-smallest-element-in-a-bst'],
  ['delete a node from a bst', 'delete-node-in-a-bst'],
  ['bst iterator', 'binary-search-tree-iterator'],
  ['inorder successor in a bst', 'inorder-successor-in-bst'],
  ['two sum in a bst', 'two-sum-iv-input-is-a-bst'],
  ['trim a bst', 'trim-a-binary-search-tree'],
  ['convert a bst to a sorted doubly linked list', 'convert-binary-search-tree-to-sorted-doubly-linked-list'],
  ['recover a bst', 'recover-binary-search-tree'],
  ['merge two bsts', 'https://www.geeksforgeeks.org/merge-two-balanced-binary-search-trees/'],
  ['balance a binary search tree', 'balance-a-binary-search-tree'],
  ['count of range sums', 'count-of-range-sum'],
  ['my calendar iii', 'my-calendar-iii'],

  /* ---- balanced trees ---- */
  ['treap', CP + 'data_structures/treap.html'],
  ['avl', 'https://www.geeksforgeeks.org/insertion-in-an-avl-tree/'],

  /* ---- tries ---- */
  ['implement a trie', 'implement-trie-prefix-tree'],
  ['add-and-search with a', 'design-add-and-search-words-data-structure'],
  ['replace words', 'replace-words'],
  ['map sum pairs', 'map-sum-pairs'],
  ['search suggestions system', 'search-suggestions-system'],
  ['design search autocomplete', 'design-search-autocomplete-system'],
  ['maximum xor of two numbers in an array', 'maximum-xor-of-two-numbers-in-an-array'],
  ['maximum xor subarray', 'https://www.geeksforgeeks.org/find-the-maximum-subarray-xor-in-a-given-array/'],
  ['word search ii', 'word-search-ii'],
  ['concatenated words', 'concatenated-words'],
  ['word break ii', 'word-break-ii'],
  ['maximum xor with an element from the array', 'maximum-xor-with-an-element-from-array'],

  /* ---- DSU ---- */
  ['implement dsu', CP + 'data_structures/disjoint_set_union.html'],
  ['number of provinces', 'number-of-provinces'],
  ['number of islands ii', 'number-of-islands-ii'],
  ['islands ii', 'number-of-islands-ii'],
  ['number of islands', 'number-of-islands'],
  ['accounts merge', 'accounts-merge'],
  ['same person, given shared emails', 'accounts-merge'],
  ['satisfiability of equality equations', 'satisfiability-of-equality-equations'],
  ['similar string groups', 'similar-string-groups'],
  ['number of operations to make a network connected', 'number-of-operations-to-make-network-connected'],
  ['most stones removed', 'most-stones-removed-with-same-row-or-column'],
  ['redundant connection ii', 'redundant-connection-ii'],
  ['redundant connection', 'redundant-connection'],
  ['evaluate division', 'evaluate-division'],
  ['swim in rising water', 'swim-in-rising-water'],
  ['smallest string with swaps', 'smallest-string-with-swaps'],
  ['edge with a length limit', 'checking-existence-of-edge-length-limited-paths'],

  /* ---- segment tree, fenwick, sparse ---- */
  ['lazy propagation', CP + 'data_structures/segment_tree.html'],
  ['persistent segment tree', CP + 'data_structures/segment_tree.html'],
  ['implement a fenwick tree', CP + 'data_structures/fenwick.html'],
  ['sparse table', CP + 'data_structures/sparse-table.html'],
  ['falling squares', 'falling-squares'],
  ['the skyline problem', 'the-skyline-problem'],
  ['skyline problem', 'the-skyline-problem'],
  ['rectangle area ii', 'rectangle-area-ii'],
  ['euler tour', CP + 'graph/lca.html'],
  ['bit bit-walk', CP + 'data_structures/fenwick.html'],
  ["mo's algorithm", CP + 'data_structures/sqrt_decomposition.html'],

  /* ---- graphs ---- */
  ['find if a path exists', 'find-if-path-exists-in-graph'],
  ['find the town judge', 'find-the-town-judge'],
  ['clone a graph', 'clone-graph'],
  ['keys and rooms', 'keys-and-rooms'],
  ['minimum number of vertices to reach all nodes', 'minimum-number-of-vertices-to-reach-all-nodes'],
  ['is the graph a valid tree', 'graph-valid-tree'],
  ['graph valid tree', 'graph-valid-tree'],
  ['word ladder ii', 'word-ladder-ii'],
  ['word ladder', 'word-ladder'],
  ['find eventual safe states', 'find-eventual-safe-states'],
  ['reorder routes', 'reorder-routes-to-make-all-paths-lead-to-the-city-zero'],
  ['course schedule ii', 'course-schedule-ii'],
  ['course schedule iii', 'course-schedule-iii'],
  ['course schedule', 'course-schedule'],
  ['courses be completed given prerequisite', 'course-schedule'],
  ['find all recipes', 'find-all-possible-recipes-from-given-supplies'],
  ['minimum semesters', 'parallel-courses'],
  ['longest path in a dag', 'longest-increasing-path-in-a-matrix'],
  ['alien dictionary', 'alien-dictionary'],
  ['sequence reconstruction', 'sequence-reconstruction'],
  ['parallel courses iii', 'parallel-courses-iii'],
  ['sort items by groups', 'sort-items-by-groups-respecting-dependencies'],
  ['largest colour value in a directed graph', 'largest-color-value-in-a-directed-graph'],
  ['longest cycle in a graph', 'longest-cycle-in-a-graph'],
  ['critical connections', 'critical-connections-in-a-network'],
  ['bridges', CP + 'graph/bridge-searching.html'],
  ['articulation points', CP + 'graph/cutpoints.html'],
  ['is the graph bipartite', 'is-graph-bipartite'],
  ['possible bipartition', 'possible-bipartition'],
  ['network delay time', 'network-delay-time'],
  ['path with maximum probability', 'path-with-maximum-probability'],
  ['path with minimum effort', 'path-with-minimum-effort'],
  ['number of ways to arrive at the destination', 'number-of-ways-to-arrive-at-destination'],
  ['minimum obstacle removal', 'minimum-obstacle-removal-to-reach-corner'],
  ['cheapest flights within k stops', 'cheapest-flights-within-k-stops'],
  ['cheapest flight from a to b with at most k stops', 'cheapest-flights-within-k-stops'],
  ['alternating edge colours', 'shortest-path-with-alternating-colors'],
  ['shortest path visiting all nodes', 'shortest-path-visiting-all-nodes'],
  ['at least one valid path in a grid', 'minimum-cost-to-make-at-least-one-valid-path-in-a-grid'],
  ['subdivided-edge budget', 'reachable-nodes-in-subdivided-graph'],
  ['city with the fewest reachable neighbours', 'find-the-city-with-the-smallest-number-of-neighbors-at-a-threshold-distance'],
  ['city with the smallest number of reachable neighbours', 'find-the-city-with-the-smallest-number-of-neighbors-at-a-threshold-distance'],
  ['bellman-ford', CP + 'graph/bellman_ford.html'],
  ['floyd-warshall', CP + 'graph/all-pair-shortest-path-floyd-warshall.html'],
  ['negative cycle', CP + 'graph/finding-negative-cycle-in-graph.html'],
  ['currency arbitrage', CP + 'graph/finding-negative-cycle-in-graph.html'],
  ["johnson's algorithm", 'https://en.wikipedia.org/wiki/Johnson%27s_algorithm'],
  ['min cost to connect all points', 'min-cost-to-connect-all-points'],
  ['connecting cities with minimum cost', 'connecting-cities-with-minimum-cost'],
  ['optimize water distribution', 'optimize-water-distribution-in-a-village'],
  ['critical and pseudo-critical edges', 'find-critical-and-pseudo-critical-edges-in-minimum-spanning-tree'],
  ['second-best mst', CP + 'graph/second_best_mst.html'],
  ['kruskal', CP + 'graph/mst_kruskal.html'],
  ['prim', CP + 'graph/mst_prim.html'],
  ['kosaraju', CP + 'graph/strongly-connected-components.html'],
  ['tarjan', CP + 'graph/strongly-connected-components.html'],
  ['condensation dag', CP + 'graph/strongly-connected-components.html'],
  ['2-sat', CP + 'graph/2SAT.html'],
  ['biconnected components', CP + 'graph/bridge-searching.html'],
  ['bus routes', 'bus-routes'],
  ['last day where it is possible to cross', 'last-day-where-you-can-still-cross'],

  /* ---- flows, matching ---- */
  ['kuhn', CP + 'graph/kuhn_maximum_bipartite_matching.html'],
  ['maximum bipartite matching', CP + 'graph/kuhn_maximum_bipartite_matching.html'],
  ['maximum number of accepted invitations', 'maximum-number-of-accepted-invitations'],
  ['campus bikes', 'campus-bikes-ii'],
  ['edmonds-karp', CP + 'graph/edmonds_karp.html'],
  ['dinic', CP + 'graph/dinic.html'],
  ['min cut', CP + 'graph/edmonds_karp.html'],
  ['könig', 'https://en.wikipedia.org/wiki/K%C5%91nig%27s_theorem_(graph_theory)'],
  ['maximum students taking an exam', 'maximum-students-taking-exam'],
  ['maximum closure', 'https://en.wikipedia.org/wiki/Closure_problem'],
  ['min-cost max flow', 'https://en.wikipedia.org/wiki/Minimum-cost_flow_problem'],
  ['hungarian', 'https://en.wikipedia.org/wiki/Hungarian_algorithm'],

  /* ---- grids ---- */
  ['flood fill', 'flood-fill'],
  ['max area of an island', 'max-area-of-island'],
  ['island perimeter', 'island-perimeter'],
  ['closed islands', 'number-of-closed-islands'],
  ['enclosed regions', 'number-of-enclaves'],
  ['01 matrix', '01-matrix'],
  ['rotting oranges', 'rotting-oranges'],
  ['walls and gates', 'walls-and-gates'],
  ['as far from land as possible', 'as-far-from-land-as-possible'],
  ['map of highest peak', 'map-of-highest-peak'],
  ['surrounded regions', 'surrounded-regions'],
  ['at most k wall removals', 'shortest-path-in-a-grid-with-obstacles-elimination'],
  ['shortest bridge', 'shortest-bridge'],
  ['shortest path to get all keys', 'shortest-path-to-get-all-keys'],
  ['word search in a grid', 'word-search'],

  /* ---- backtracking ---- */
  ['combinations (n choose k)', 'combinations'],
  ['combination sum iv', 'combination-sum-iv'],
  ['combination sum i, ii and iii', 'combination-sum'],
  ['letter combinations of a phone number', 'letter-combinations-of-a-phone-number'],
  ['palindrome partitioning ii', 'palindrome-partitioning-ii'],
  ['palindrome partitioning', 'palindrome-partitioning'],
  ['restore ip addresses', 'restore-ip-addresses'],
  ['letter case permutation', 'letter-case-permutation'],
  ['n-queens ii', 'n-queens-ii'],
  ['n-queens', 'n-queens'],
  ['sudoku solver', 'sudoku-solver'],
  ['partition to k equal-sum subsets', 'partition-to-k-equal-sum-subsets'],
  ['partition into k subsets of equal sum', 'partition-to-k-equal-sum-subsets'],
  ['matchsticks to square', 'matchsticks-to-square'],
  ['expression add operators', 'expression-add-operators'],
  ['24 game', '24-game'],

  /* ---- greedy ---- */
  ['assign cookies', 'assign-cookies'],
  ['boats to save people', 'boats-to-save-people'],
  ['can place flowers', 'can-place-flowers'],
  ['non-overlapping intervals', 'non-overlapping-intervals'],
  ['minimum arrows to burst balloons', 'minimum-number-of-arrows-to-burst-balloons'],
  ['jump game ii', 'jump-game-ii'],
  ['jump game', 'jump-game'],
  ['gas station', 'gas-station'],
  ['smallest subsequence of distinct characters', 'smallest-subsequence-of-distinct-characters'],
  ['huffman', 'https://www.geeksforgeeks.org/huffman-coding-greedy-algo-3/'],
  ['candy distribution', 'candy'],
  ['refuelling stops', 'minimum-number-of-refueling-stops'],

  /* ---- divide and conquer ---- */
  ['majority element', 'majority-element'],
  ['maximum subarray', 'maximum-subarray'],
  ['different ways to add parentheses', 'different-ways-to-add-parentheses'],
  ['beautiful array', 'beautiful-array'],
  ['construct a quad tree', 'construct-quad-tree'],
  ['construct a bst from preorder', 'construct-binary-search-tree-from-preorder-traversal'],
  ['matrix exponentiation', CP + 'algebra/binary-exp.html'],
  ['adjacency-matrix powers', CP + 'algebra/binary-exp.html'],
  ['closest pair of points', CP + 'geometry/nearest_points.html'],
  ['karatsuba', 'https://en.wikipedia.org/wiki/Karatsuba_algorithm'],

  /* ---- DP ---- */
  ['climbing stairs', 'climbing-stairs'],
  ['min cost climbing stairs', 'min-cost-climbing-stairs'],
  ['house robber ii', 'house-robber-ii'],
  ['house robber i and ii', 'house-robber-ii'],
  ['house robber', 'house-robber'],
  ['unique paths; then with obstacles', 'unique-paths-ii'],
  ['unique paths', 'unique-paths'],
  ['decode ways', 'decode-ways'],
  ['word break', 'word-break'],
  ['best time to buy and sell stock iv', 'best-time-to-buy-and-sell-stock-iv'],
  ['best time to buy and sell stock iii', 'best-time-to-buy-and-sell-stock-iii'],
  ['best time to buy and sell stock ii', 'best-time-to-buy-and-sell-stock-ii'],
  ['best time to buy and sell stock i', 'best-time-to-buy-and-sell-stock'],
  ['stock ii', 'best-time-to-buy-and-sell-stock-ii'],
  ['stock iii', 'best-time-to-buy-and-sell-stock-iii'],
  ['stock iv', 'best-time-to-buy-and-sell-stock-iv'],
  ['stock with cooldown', 'best-time-to-buy-and-sell-stock-with-cooldown'],
  ['with cooldown', 'best-time-to-buy-and-sell-stock-with-cooldown'],
  ['transaction fee', 'best-time-to-buy-and-sell-stock-with-transaction-fee'],
  ['maximum product subarray', 'maximum-product-subarray'],
  ['maximum sum circular subarray', 'maximum-sum-circular-subarray'],
  ['lis both ways', 'longest-increasing-subsequence'],
  ['number of lis', 'number-of-longest-increasing-subsequence'],
  ['longest arithmetic subsequence', 'longest-arithmetic-subsequence'],
  ['integer break', 'integer-break'],
  ['perfect squares', 'perfect-squares'],
  ['delete and earn', 'delete-and-earn'],
  ['longest string chain', 'longest-string-chain'],
  ['russian doll envelopes', 'russian-doll-envelopes'],
  ['reconstruct the actual lis', 'longest-increasing-subsequence'],
  ['0/1 knapsack', CP + 'dynamic_programming/knapsack.html'],
  ['partition equal subset sum', 'partition-equal-subset-sum'],
  ['target sum', 'target-sum'],
  ['coin change (minimum) and coin change ii', 'coin-change-ii'],
  ['coin change', 'coin-change'],
  ['make change for amount n with given coins', 'coin-change-ii'],
  ['minimum subset sum difference', 'last-stone-weight-ii'],
  ['ones and zeroes', 'ones-and-zeroes'],
  ['rod cutting', 'https://www.geeksforgeeks.org/cutting-a-rod-dp-13/'],
  ['profitable schemes', 'profitable-schemes'],
  ['number of dice rolls with target sum', 'number-of-dice-rolls-with-target-sum'],
  ['meet in the middle', 'https://en.wikipedia.org/wiki/Meet-in-the-middle_attack'],

  ['longest common subsequence', 'longest-common-subsequence'],
  ['edit distance', 'edit-distance'],
  ['delete operation for two strings', 'delete-operation-for-two-strings'],
  ['minimum ascii delete sum', 'minimum-ascii-delete-sum-for-two-strings'],
  ['shortest common supersequence', 'shortest-common-supersequence'],
  ['longest palindromic subsequence', 'longest-palindromic-subsequence'],
  ['minimum insertions to make a palindrome', 'minimum-insertion-steps-to-make-a-string-palindrome'],
  ['count palindromic substrings', 'palindromic-substrings'],
  ['longest common substring', 'https://www.geeksforgeeks.org/longest-common-substring-dp-29/'],
  ['interleaving', 'interleaving-string'],
  ['wildcard matching', 'wildcard-matching'],
  ['regular expression matching', 'regular-expression-matching'],
  ['distinct subsequences', 'distinct-subsequences'],

  ['minimum path sum', 'minimum-path-sum'],
  ['triangle — minimum falling path', 'triangle'],
  ['minimum falling path sum ii', 'minimum-falling-path-sum-ii'],
  ['maximal square', 'maximal-square'],
  ['count all square submatrices', 'count-square-submatrices-with-all-ones'],
  ['cherry pickup ii', 'cherry-pickup-ii'],
  ['cherry pickup', 'cherry-pickup'],
  ['dungeon game', 'dungeon-game'],

  ['held-karp', 'https://en.wikipedia.org/wiki/Held%E2%80%93Karp_algorithm'],
  ['shortest superstring', 'find-the-shortest-superstring'],
  ['minimum number of work sessions', 'minimum-number-of-work-sessions-to-finish-the-tasks'],
  ['maximum compatibility score sum', 'maximum-compatibility-score-sum'],
  ['wear different hats', 'number-of-ways-to-wear-different-hats-to-each-other'],
  ['domino tiling', 'domino-and-tromino-tiling'],
  ['broken-profile', 'https://cp-algorithms.com/dynamic_programming/profile-dynamics.html'],
  ['smallest sufficient team', 'smallest-sufficient-team'],
  ['minimum-cost assignment', 'https://en.wikipedia.org/wiki/Assignment_problem'],
  ['assign n ≤ 16 jobs', 'https://en.wikipedia.org/wiki/Assignment_problem'],

  ['matrix chain multiplication', 'https://www.geeksforgeeks.org/matrix-chain-multiplication-dp-8/'],
  ['minimum cost to cut a stick', 'minimum-cost-to-cut-a-stick'],
  ['burst balloons', 'burst-balloons'],
  ['merge stones', 'minimum-cost-to-merge-stones'],
  ['merge n ≤ 300 stones', 'minimum-cost-to-merge-stones'],
  ['minimum score triangulation', 'minimum-score-triangulation-of-polygon'],
  ['strange printer', 'strange-printer'],
  ['remove boxes', 'remove-boxes'],
  ['predict the winner', 'predict-the-winner'],
  ['optimal binary search tree', 'https://www.geeksforgeeks.org/optimal-binary-search-tree-dp-24/'],
  ['knuth optimisation', CP + 'dynamic_programming/knuth-optimization.html'],

  ['no consecutive equal digits', 'https://cp-algorithms.com/dynamic_programming/intro-to-dp.html'],
  ['numbers at most n built from a given digit set', 'numbers-at-most-n-given-digit-set'],
  ['count monotone digits', 'monotone-increasing-digits'],
  ['count the digit "1"', 'number-of-digit-one'],
  ['knight probability', 'knight-probability-in-chessboard'],
  ['new 21 game', 'new-21-game'],
  ['soup servings', 'soup-servings'],
  ['dice roll simulation', 'dice-roll-simulation'],
  ['stone game iii and iv', 'stone-game-iii'],
  ['stone game i and ii', 'stone-game-ii'],
  ['stone game', 'stone-game'],
  ['can i win', 'can-i-win'],
  ['divisor game', 'divisor-game'],
  ['nim', 'nim-game'],
  ['cat and mouse', 'cat-and-mouse'],
  ['no two adjacent equal digits', 'https://cp-algorithms.com/dynamic_programming/intro-to-dp.html'],

  /* ---- bit manipulation ---- */
  ['number of 1 bits', 'number-of-1-bits'],
  ['power of two', 'power-of-two'],
  ['power of four', 'power-of-four'],
  ['single number iii', 'single-number-iii'],
  ['single number ii', 'single-number-ii'],
  ['single number', 'single-number'],
  ['missing number', 'missing-number'],
  ['counting bits', 'counting-bits'],
  ['reverse bits', 'reverse-bits'],
  ['number complement', 'number-complement'],
  ['gray code', 'gray-code'],
  ['maximum product of word lengths', 'maximum-product-of-word-lengths'],
  ['palindrome permutation', 'palindrome-permutation'],
  ['find the difference', 'find-the-difference'],
  ['sum of two integers', 'sum-of-two-integers'],
  ['bitwise and of a number range', 'bitwise-and-of-numbers-range'],
  ['concatenation of consecutive binary numbers', 'concatenation-of-consecutive-binary-numbers'],

  /* ---- maths ---- */
  ['gcd of an array', CP + 'algebra/euclid-algorithm.html'],
  ['count primes', 'count-primes'],
  ['smallest prime factor table', CP + 'algebra/sieve-of-eratosthenes.html'],
  ['modular power', CP + 'algebra/binary-exp.html'],
  ['ncr mod', CP + 'combinatorics/binomial-coefficients.html'],
  ['modular inverse', CP + 'algebra/module-inverse.html'],
  ['fraction to recurring decimal', 'fraction-to-recurring-decimal'],
  ["euler's totient", CP + 'algebra/phi-function.html'],
  ['inclusion-exclusion', CP + 'combinatorics/inclusion-exclusion.html'],
  ['water and jug', 'water-and-jug-problem'],
  ['catalan numbers', CP + 'combinatorics/catalan-numbers.html'],
  ['extended euclid', CP + 'algebra/extended-euclid-algorithm.html'],

  /* ---- geometry, randomisation ---- */
  ['three points are collinear', 'valid-boomerang'],
  ['is a polygon convex', 'convex-polygon'],
  ['convex hull', CP + 'geometry/convex-hull.html'],
  ['interval list intersections', 'interval-list-intersections'],
  ['maximum population year', 'maximum-population-year'],
  ['linked list random node', 'linked-list-random-node'],
  ['random pick with weight', 'random-pick-with-weight'],
  ['shuffle an array', 'shuffle-an-array'],
  ['random point in a non-overlapping rectangle', 'random-point-in-non-overlapping-rectangles'],
  ['random point in non-overlapping rectangles', 'random-point-in-non-overlapping-rectangles'],
  ['shoelace', CP + 'geometry/area-of-simple-polygon.html'],
  ['segments intersect', CP + 'geometry/check-segments-intersection.html'],

  /* ---- string algorithms ---- */
  ['strstr', 'find-the-index-of-the-first-occurrence-in-a-string'],
  ['build lps', CP + 'string/prefix-function.html'],
  ['repeated substring pattern', 'repeated-substring-pattern'],
  ['shortest period of a string', CP + 'string/prefix-function.html'],
  ['shortest palindrome by prepending', 'shortest-palindrome'],
  ['z-function', CP + 'string/z-function.html'],
  ['rabin-karp', CP + 'string/string-hashing.html'],
  ['repeated dna sequences', 'repeated-dna-sequences'],
  ['longest duplicate substring', 'longest-duplicate-substring'],
  ['manacher', CP + 'string/manacher.html'],
  ['suffix array', CP + 'string/suffix-array.html'],
  ['aho-corasick', CP + 'string/aho_corasick.html'],
  ['stream checker', 'stream-of-characters'],

  /* ---- design ---- */
  ['lru cache', 'lru-cache'],
  ['lfu cache', 'lfu-cache'],
  ['time-based key-value store', 'time-based-key-value-store'],
  ['snapshot array', 'snapshot-array'],
  ['design a hit counter', 'design-hit-counter'],
  ['logger rate limiter', 'logger-rate-limiter'],
  ['browser history', 'design-browser-history'],
  ['a file system', 'design-file-system'],
  ['skip list', 'design-skiplist'],
  ['bloom filter', 'https://en.wikipedia.org/wiki/Bloom_filter'],
  ['count distinct values in a range', CP + 'data_structures/sqrt_decomposition.html'],

  /* ---- walkthrough extras ---- */
  ['maximum sum of two non-overlapping subarrays', 'maximum-sum-of-two-non-overlapping-subarrays'],
  ['slope-trick', 'https://cp-algorithms.com/others/tortoise_and_hare.html'],
  ['bottleneck queries', CP + 'graph/mst_kruskal.html'],
  /* ---- added after the first dry run: unmatched items worth linking ---- */
  ['string is a palindrome recursively', 'valid-palindrome'],
  ['implement a min-heap from scratch', 'https://www.geeksforgeeks.org/binary-heap/'],
  ['all three traversals, recursively', 'binary-tree-inorder-traversal'],
  ['rewrite the same tree for max and gcd', CP + 'data_structures/segment_tree.html'],
  ['range assign plus range add', CP + 'data_structures/segment_tree.html'],
  ['difference-array trick inside a bit', CP + 'data_structures/fenwick.html'],
  ['range sum with two bits', CP + 'data_structures/fenwick.html'],
  ['dfs and bfs traversal of a graph', CP + 'graph/breadth-first-search.html'],
  ['shortest path in an unweighted graph with bfs', CP + 'graph/breadth-first-search.html'],
  ['shortest distance from a source in an unweighted graph', CP + 'graph/breadth-first-search.html'],
  ['implement toposort both ways', CP + 'graph/topological-sort.html'],
  ['detect a cycle in a directed graph', CP + 'graph/finding-cycle.html'],
  ['detect a cycle in an undirected graph', CP + 'graph/finding-cycle.html'],
  ['return the actual cycle nodes', CP + 'graph/finding-cycle.html'],
  ['shortest cycle (girth)', CP + 'graph/finding-cycle.html'],
  ['contain an odd cycle', 'is-graph-bipartite'],
  ['dsu with parity', CP + 'data_structures/disjoint_set_union.html'],
  ['transitive closure', CP + 'graph/all-pair-shortest-path-floyd-warshall.html'],
  ['maximum spanning tree', CP + 'graph/mst_kruskal.html'],
  ['largest scc', CP + 'graph/strongly-connected-components.html'],
  ['node-capacity flow', CP + 'graph/edmonds_karp.html'],
  ['exactly k moves', 'out-of-boundary-paths'],
  ['diameter of a general n-ary tree', 'tree-diameter'],
  ['digit sum is divisible by m', CP + 'dynamic_programming/intro-to-dp.html'],
];
