/* =========================================================
   tools/chapters.cjs — the LLD chapter plan.

   Source for tools/scaffold.cjs, which writes the CHAPTERS
   registry into assets/app.js and creates a placeholder page
   for every chapter that doesn't exist yet. Once a chapter is
   written, assets/app.js is the source of truth for its
   title/blurb; `cover` is only the planned outline.

     hld   a System Design chapter covering the same problem at
           the architecture level (linked from the case study)
   ========================================================= */
'use strict';

const P = 'Prerequisites', PR = 'Principles', DP = 'Design Patterns', AD = 'Advanced LLD', CS = 'Case Studies';

module.exports = [
  // ---------- Prerequisites: the Java OOP the course assumes ----------
  { n: 0.1, slug: 'p1-classes-objects', title: 'Classes, Objects & References', level: P, icon: '🧱', mins: 40,
    blurb: 'How a Java class becomes objects on the heap, references vs values, constructors and the object lifecycle.',
    cover: ['Fields, methods and constructors', 'Stack vs heap: where a reference and its object live', 'Pass-by-value of references (the swap that doesn\'t swap)', 'static members and when they belong', 'Garbage collection in one picture'] },
  { n: 0.2, slug: 'p2-encapsulation', title: 'Encapsulation & Invariants', level: P, icon: '🔒', mins: 35,
    blurb: 'Access modifiers, why public fields break invariants, and getters that don\'t leak internal state.',
    cover: ['private / package-private / protected / public', 'Class invariants: what must always be true', 'Defensive copies of mutable fields', 'Tell, don\'t ask'] },
  { n: 0.3, slug: 'p3-inheritance-dispatch', title: 'Inheritance & Dynamic Dispatch', level: P, icon: '🧬', mins: 45,
    blurb: 'extends, super, overriding vs overloading, and how the JVM picks which method runs at runtime.',
    cover: ['extends and super()', 'Overriding vs overloading', 'Dynamic dispatch and the vtable', 'final classes and methods', 'The fragile base class problem'] },
  { n: 0.4, slug: 'p4-interfaces-generics', title: 'Interfaces, Abstract Classes & Generics', level: P, icon: '🔌', mins: 45,
    blurb: 'Programming to an interface, default methods, abstract base classes, and type-safe generics with bounds.',
    cover: ['Interfaces vs abstract classes', 'Default and static interface methods', 'Generic classes and methods', 'Bounded types and wildcards (PECS)', 'Functional interfaces and lambdas'] },
  { n: 0.5, slug: 'p5-composition', title: 'Composition over Inheritance', level: P, icon: '🧩', mins: 35,
    blurb: 'Why "has-a" usually beats "is-a": refactoring a subclass explosion into small composed parts.',
    cover: ['The subclass explosion', 'Delegation by hand', 'Is-a vs has-a: the substitution test', 'When inheritance is still right'] },
  { n: 0.6, slug: 'p6-value-objects', title: 'Value Objects, Enums & Immutability', level: P, icon: '💎', mins: 40,
    blurb: 'equals/hashCode contracts, records, enums with behaviour, and why immutable objects are thread-safe for free.',
    cover: ['equals and hashCode, and the HashMap bug when they disagree', 'Records', 'Enums with fields and methods', 'Making a class immutable', 'Collections.unmodifiableList vs List.copyOf'] },
  { n: 0.7, slug: 'p7-exceptions', title: 'Exceptions & Error Contracts', level: P, icon: '⚠️', mins: 35,
    blurb: 'Checked vs unchecked exceptions, custom exception types, try-with-resources and Optional.',
    cover: ['Checked vs unchecked', 'Designing an exception hierarchy', 'try-with-resources and AutoCloseable', 'Optional instead of null', 'Fail fast at the boundary'] },
  { n: 0.8, slug: 'p8-reading-uml', title: 'Reading UML: Class & Sequence Diagrams', level: P, icon: '📐', mins: 40,
    blurb: 'The small subset of UML interviewers expect: classes, relationships, multiplicities and sequence diagrams.',
    cover: ['Class boxes: fields, methods, visibility', 'Association, aggregation, composition, inheritance, realization', 'Multiplicities', 'Sequence diagrams: lifelines, calls, returns', 'Diagram ↔ Java code, both directions'] },

  // ---------- Principles ----------
  { n: 1, slug: '01-lld-interview', title: 'What an LLD Interview Tests', level: PR, icon: '🧭', mins: 30,
    blurb: 'The 45-minute flow — requirements, entities, classes, APIs, code, extension — and the house style for every Java listing.',
    cover: ['LLD vs HLD vs DSA rounds', 'The 45-minute timeline', 'What the rubric actually scores', 'The course\'s Java house style'] },
  { n: 2, slug: '02-requirements-to-classes', title: 'From Requirements to Classes', level: PR, icon: '📝', mins: 40,
    blurb: 'Noun/verb extraction, use cases and scope cuts: turning a vague prompt into a first class list.',
    cover: ['Clarifying questions that change the design', 'Nouns → candidate classes, verbs → methods', 'Use cases and actors', 'Cutting scope out loud', 'Worked example: a URL shortener\'s core classes'] },
  { n: 3, slug: '03-solid-srp-ocp', title: 'SOLID I: Single Responsibility & Open/Closed', level: PR, icon: '🎯', mins: 45,
    blurb: 'Splitting a god-class ReportService, and adding new export formats without editing old code.',
    cover: ['Reasons to change, not "one thing"', 'Spotting a god class', 'Open for extension via polymorphism', 'When OCP is over-engineering'] },
  { n: 4, slug: '04-solid-lsp-isp-dip', title: 'SOLID II: Liskov, Interface Segregation & Dependency Inversion', level: PR, icon: '🔁', mins: 45,
    blurb: 'Why an unmodifiable list breaks List, fat repository interfaces, and depending on abstractions.',
    cover: ['Liskov: behavioural subtyping', 'The UnsupportedOperationException smell', 'Role interfaces', 'Dependency inversion and the stable-abstractions rule'] },
  { n: 5, slug: '05-coupling-cohesion', title: 'Coupling, Cohesion & the Law of Demeter', level: PR, icon: '🕸️', mins: 40,
    blurb: 'Measuring how tangled a design is, train-wreck calls, and DRY/KISS/YAGNI without the slogans.',
    cover: ['Kinds of coupling', 'Cohesion: what belongs together', 'Law of Demeter and train wrecks', 'DRY vs the wrong abstraction', 'YAGNI in an interview'] },
  { n: 6, slug: '06-relationships', title: 'Modeling Relationships', level: PR, icon: '🔗', mins: 40,
    blurb: 'Association, aggregation and composition in Java code, multiplicities, and who owns whose lifecycle.',
    cover: ['Association vs aggregation vs composition', 'One-to-many and many-to-many in Java', 'Bidirectional links and their cost', 'Ownership and lifecycle'] },
  { n: 7, slug: '07-class-contracts', title: 'Class APIs & Contracts', level: PR, icon: '📜', mins: 40,
    blurb: 'Preconditions, postconditions, fail-fast validation, and designing method signatures that can\'t be misused.',
    cover: ['Pre- and postconditions', 'Validate at the boundary', 'Hard-to-misuse signatures', 'Command-query separation', 'Return types: null, Optional or exception'] },
  { n: 8, slug: '08-dependency-injection', title: 'Dependency Injection & Testability', level: PR, icon: '💉', mins: 40,
    blurb: 'Constructor injection, composition roots, and swapping a real database for an in-memory fake.',
    cover: ['new is glue', 'Constructor vs setter injection', 'The composition root', 'Fakes vs mocks', 'DI without a framework'] },

  // ---------- Design Patterns ----------
  { n: 9, slug: '09-singleton', title: 'Singleton (and Why It\'s Usually Wrong)', level: DP, icon: '☝️', mins: 35,
    blurb: 'Thread-safe lazy init, the enum singleton, double-checked locking — and why DI usually replaces it.',
    cover: ['Eager, lazy and holder-class singletons', 'Double-checked locking and volatile', 'The enum singleton', 'Global state and testability'] },
  { n: 10, slug: '10-factories', title: 'Factory Method & Abstract Factory', level: DP, icon: '🏭', mins: 45,
    blurb: 'A JDBC-style driver factory, static factory methods, and families of related objects.',
    cover: ['Static factory methods', 'Factory Method', 'Abstract Factory for product families', 'Registries instead of switch statements'] },
  { n: 11, slug: '11-builder-prototype', title: 'Builder & Prototype', level: DP, icon: '🧰', mins: 40,
    blurb: 'An HTTP request builder, a SQL query builder, and cloning objects without constructors.',
    cover: ['Telescoping constructors', 'Builder with validation in build()', 'Fluent APIs', 'Prototype and copy constructors'] },
  { n: 12, slug: '12-adapter-facade-bridge', title: 'Adapter, Facade & Bridge', level: DP, icon: '🔌', mins: 45,
    blurb: 'Wrapping two payment SDKs behind one interface, simplifying a subsystem, and splitting abstraction from implementation.',
    cover: ['Object adapter vs class adapter', 'Facade over a messy subsystem', 'Bridge: two dimensions of variation', 'Anti-corruption layers'] },
  { n: 13, slug: '13-decorator-proxy', title: 'Decorator & Proxy', level: DP, icon: '🎁', mins: 45,
    blurb: 'Buffered and gzip I/O streams, caching and lazy-loading proxies, and how java.io is built.',
    cover: ['Decorator: stacking behaviour', 'How java.io streams compose', 'Proxy: caching, lazy loading, access control', 'Dynamic proxies'] },
  { n: 14, slug: '14-composite-flyweight', title: 'Composite & Flyweight', level: DP, icon: '🌳', mins: 40,
    blurb: 'File-system trees and DOM nodes as composites, and sharing glyph objects with flyweights.',
    cover: ['Composite: treat one and many the same', 'File-system and UI trees', 'Flyweight: intrinsic vs extrinsic state', 'Integer.valueOf caching'] },
  { n: 15, slug: '15-strategy', title: 'Strategy', level: DP, icon: '♟️', mins: 40,
    blurb: 'Swappable load-balancer policies, rate-limit algorithms and comparators — the pattern you\'ll use most.',
    cover: ['Strategy vs if/else chains', 'Strategies as lambdas', 'Choosing a strategy at runtime', 'Comparator as Strategy'] },
  { n: 16, slug: '16-observer-mediator', title: 'Observer & Mediator', level: DP, icon: '📣', mins: 45,
    blurb: 'An in-process event bus, UI listeners, and a mediator that stops components talking to each other directly.',
    cover: ['Observer: subjects and listeners', 'Push vs pull notifications', 'Memory leaks from forgotten listeners', 'Mediator for many-to-many chatter'] },
  { n: 17, slug: '17-command-memento', title: 'Command & Memento', level: DP, icon: '↩️', mins: 45,
    blurb: 'Undo/redo in an editor, queued jobs as objects, and snapshotting state without breaking encapsulation.',
    cover: ['Command objects', 'Undo/redo stacks', 'Job queues and macros', 'Memento: saving state safely'] },
  { n: 18, slug: '18-state', title: 'State', level: DP, icon: '🚦', mins: 40,
    blurb: 'A TCP connection and an order lifecycle as state machines, and replacing flag soup with state objects.',
    cover: ['Flag soup', 'State objects and transitions', 'Enum-based state machines', 'State vs Strategy'] },
  { n: 19, slug: '19-chain-template', title: 'Chain of Responsibility & Template Method', level: DP, icon: '⛓️', mins: 40,
    blurb: 'An HTTP middleware pipeline, request validators, and fixing an algorithm\'s skeleton while varying its steps.',
    cover: ['Handler chains', 'Servlet filters and middleware', 'Template Method and hooks', 'Template Method vs Strategy'] },
  { n: 20, slug: '20-iterator-visitor', title: 'Iterator & Visitor', level: DP, icon: '🧭', mins: 40,
    blurb: 'Custom Iterable collections, and evaluating a small expression AST with a visitor.',
    cover: ['Iterable and Iterator', 'Fail-fast iterators', 'Visitor and double dispatch', 'Visitor vs sealed types + pattern matching'] },
  { n: 21, slug: '21-patterns-together', title: 'Patterns Together & Anti-Patterns', level: DP, icon: '🧪', mins: 40,
    blurb: 'Combining patterns in one design, spotting over-engineering, and when a plain function is the answer.',
    cover: ['Patterns that pair naturally', 'Over-engineering smells', 'Anemic domain models', '"Pattern or plain function?" drill'] },

  // ---------- Advanced LLD ----------
  { n: 22, slug: '22-thread-safe-classes', title: 'Thread-Safe Class Design', level: AD, icon: '🔐', mins: 50,
    blurb: 'Locks, immutability and confinement; synchronized vs ReentrantLock; and visualising a race condition.',
    cover: ['Races and check-then-act', 'synchronized, volatile and ReentrantLock', 'Immutability and confinement', 'java.util.concurrent collections', 'Lock ordering and deadlock'] },
  { n: 23, slug: '23-producer-consumer', title: 'Producer-Consumer, Thread Pools & Futures', level: AD, icon: '🏭', mins: 50,
    blurb: 'BlockingQueue with backpressure, ExecutorService sizing, and CompletableFuture pipelines.',
    cover: ['BlockingQueue and backpressure', 'ExecutorService and pool sizing', 'Futures and CompletableFuture', 'Graceful shutdown'] },
  { n: 24, slug: '24-extensibility', title: 'Designing for Extensibility', level: AD, icon: '🧩', mins: 40,
    blurb: 'Plugin registries, ServiceLoader, configuration-driven behaviour and feature flags.',
    cover: ['Extension points', 'Plugin registries and ServiceLoader', 'Config-driven behaviour', 'Feature flags in code'] },
  { n: 25, slug: '25-resilience', title: 'Resilience at the Class Level', level: AD, icon: '🛡️', mins: 40,
    blurb: 'A retry policy object, a circuit-breaker state machine, timeouts and idempotency keys.',
    cover: ['Retry with backoff and jitter', 'Circuit breaker as a state machine', 'Timeouts and bulkheads', 'Idempotency'] },
  { n: 26, slug: '26-persistence', title: 'Persistence: Repository, DAO & Unit of Work', level: AD, icon: '🗄️', mins: 45,
    blurb: 'Keeping SQL out of the domain, mapping an aggregate onto tables, and transactional boundaries.',
    cover: ['DAO vs Repository', 'Mapping objects to tables', 'Unit of Work and transactions', 'In-memory repositories for tests'] },
  { n: 27, slug: '27-domain-modeling', title: 'Domain Modeling (DDD Lite)', level: AD, icon: '🏛️', mins: 45,
    blurb: 'Entities, value objects, aggregates and domain events — the parts of DDD that pay off in an interview.',
    cover: ['Entities vs value objects', 'Aggregates and invariants', 'Domain events', 'Services: domain vs application'] },
  { n: 28, slug: '28-testing-designs', title: 'Testing a Design', level: AD, icon: '🧪', mins: 40,
    blurb: 'JUnit tests for a design, fakes vs mocks vs stubs, and injecting clocks and randomness.',
    cover: ['What to test in LLD', 'Test doubles', 'Injecting Clock and Random', 'Tests as a design check'] },
  { n: 29, slug: '29-smells-refactoring', title: 'Code Smells & Refactoring', level: AD, icon: '🧹', mins: 45,
    blurb: 'Long methods, feature envy, switch statements and primitive obsession — each refactored into a pattern.',
    cover: ['A catalogue of smells', 'Refactoring in small safe steps', 'Replace conditional with polymorphism', 'Introduce parameter object'] },
  { n: 30, slug: '30-interview-playbook', title: 'The LLD Interview Playbook', level: AD, icon: '🎤', mins: 45,
    blurb: 'The rubric, time boxing, handling "now add X" follow-ups, and what separates hire from no-hire.',
    cover: ['The scoring rubric', 'Time boxing the 45 minutes', 'Handling extension follow-ups', 'Common failure modes'] },

  // ---------- Case Studies ----------
  { n: 31, slug: '31-case-lru-cache', title: 'Case Study: LRU & LFU Cache', level: CS, icon: '⚡', mins: 50, hld: '06-caching.html',
    blurb: 'A HashMap plus a doubly linked list for O(1) get/put, eviction as a pluggable strategy, and thread safety.',
    cover: ['Requirements and API', 'HashMap + doubly linked list', 'Eviction policy as Strategy', 'LFU with frequency buckets', 'Making it thread-safe'] },
  { n: 32, slug: '32-case-rate-limiter', title: 'Case Study: Rate Limiter', level: CS, icon: '🚥', mins: 50,
    blurb: 'Token bucket, fixed and sliding windows behind one interface, per-client state, and concurrent access.',
    cover: ['Requirements and API', 'Algorithms as strategies', 'Per-client buckets', 'Clock injection for tests', 'Concurrency'] },
  { n: 33, slug: '33-case-logger', title: 'Case Study: Logging Framework', level: CS, icon: '🪵', mins: 45,
    blurb: 'Levels, appenders and formatters; a chain of handlers; async logging without losing messages.',
    cover: ['Requirements and API', 'Levels and filtering', 'Appenders and formatters', 'Async logging with a queue', 'Configuration'] },
  { n: 34, slug: '34-case-pub-sub', title: 'Case Study: In-Memory Pub-Sub Broker', level: CS, icon: '📬', mins: 50, hld: '14-message-queues.html',
    blurb: 'Topics, subscribers, consumer offsets and bounded queues — Kafka\'s core ideas in one JVM.',
    cover: ['Requirements and API', 'Topics and partitions', 'Consumer offsets and replay', 'Bounded queues and backpressure', 'Thread model'] },
  { n: 35, slug: '35-case-task-scheduler', title: 'Case Study: Task Scheduler', level: CS, icon: '⏰', mins: 50, hld: '38-case-job-scheduler.html',
    blurb: 'One-off, delayed and recurring jobs on a priority queue, a worker pool, retries and cancellation.',
    cover: ['Requirements and API', 'DelayQueue / priority queue by run time', 'Jobs as Commands', 'Worker pool', 'Retries and cancellation'] },
  { n: 36, slug: '36-case-file-system', title: 'Case Study: In-Memory File System', level: CS, icon: '📁', mins: 45, hld: '33-case-file-sync.html',
    blurb: 'Files and directories as a composite, path resolution, mkdir -p, ls and permissions.',
    cover: ['Requirements and API', 'Composite: File and Directory', 'Path resolution', 'Operations: mkdir, ls, cat, rm', 'Permissions'] },
  { n: 37, slug: '37-case-kv-transactions', title: 'Case Study: Key-Value Store with Transactions', level: CS, icon: '🔑', mins: 50, hld: '39-case-kv-store.html',
    blurb: 'GET/SET/DELETE with nested BEGIN, COMMIT and ROLLBACK, plus TTLs and a write-ahead log.',
    cover: ['Requirements and API', 'Nested transactions as a stack of change sets', 'Rollback via Memento', 'TTL expiry', 'Write-ahead log'] },
  { n: 38, slug: '38-case-text-editor', title: 'Case Study: Text Editor with Undo/Redo', level: CS, icon: '📝', mins: 50, hld: '34-case-collab-editing.html',
    blurb: 'A gap buffer, edit commands, undo/redo stacks, and grouping keystrokes into one undo step.',
    cover: ['Requirements and API', 'Gap buffer vs rope', 'Edits as Commands', 'Undo/redo and coalescing', 'Cursor and selection'] },
  { n: 39, slug: '39-case-connection-pool', title: 'Case Study: Connection Pool', level: CS, icon: '🏊', mins: 45,
    blurb: 'Blocking acquire with timeouts, validating idle connections, leak detection and sizing.',
    cover: ['Requirements and API', 'Object pool with a semaphore', 'Acquire timeouts', 'Validation and eviction', 'Leak detection'] },
  { n: 40, slug: '40-case-parking-lot', title: 'Case Study: Parking Lot', level: CS, icon: '🅿️', mins: 45,
    blurb: 'Levels, spot types and vehicles, allocation as a strategy, tickets, fees and concurrent entry gates.',
    cover: ['Requirements and API', 'Entities and relationships', 'Spot allocation strategy', 'Tickets and pricing', 'Concurrent gates'] },
  { n: 41, slug: '41-case-elevator', title: 'Case Study: Elevator System', level: CS, icon: '🛗', mins: 50,
    blurb: 'Car state machines, SCAN/LOOK dispatch as a strategy, and a live simulator of requests.',
    cover: ['Requirements and API', 'Elevator car as a State machine', 'Dispatch strategies: nearest car, SCAN, LOOK', 'Request queues', 'Simulation loop'] },
  { n: 42, slug: '42-case-movie-ticketing', title: 'Case Study: Movie Ticket Booking', level: CS, icon: '🎟️', mins: 50, hld: '36-case-ticketing.html',
    blurb: 'Shows, screens and seats, temporary seat holds with expiry, and preventing double booking.',
    cover: ['Requirements and API', 'Entities: movie, show, screen, seat, booking', 'Seat holds with expiry', 'Preventing double booking', 'Payment and booking states'] },
  { n: 43, slug: '43-case-splitwise', title: 'Case Study: Expense Sharing (Splitwise)', level: CS, icon: '💸', mins: 45,
    blurb: 'Equal, exact and percentage splits as strategies, balance sheets, and simplifying debts.',
    cover: ['Requirements and API', 'Split types as strategies', 'Balance sheet', 'Debt simplification', 'Groups and history'] },
  { n: 44, slug: '44-case-chess', title: 'Case Study: Chess', level: CS, icon: '♞', mins: 50,
    blurb: 'Polymorphic pieces, move validation, check detection, and move history as commands.',
    cover: ['Requirements and API', 'Board, pieces and players', 'Move generation per piece', 'Check and checkmate', 'Move history and undo'] },
  { n: 45, slug: '45-case-vending-atm', title: 'Case Study: Vending Machine & ATM', level: CS, icon: '🏧', mins: 45,
    blurb: 'Machine states, inventory, and dispensing cash through a chain of denomination handlers.',
    cover: ['Requirements and API', 'Vending machine as a State machine', 'Inventory and change-making', 'ATM cash dispenser as a Chain of Responsibility', 'Failure handling'] },
  { n: 46, slug: '46-case-ride-hailing', title: 'Case Study: Ride-Hailing (LLD)', level: CS, icon: '🚕', mins: 50, hld: '35-case-ride-hailing.html',
    blurb: 'Riders, drivers and trips; matching as a strategy; trip state and observers for live updates.',
    cover: ['Requirements and API', 'Entities and trip lifecycle', 'Driver matching strategy', 'Pricing and surge', 'Observers for trip updates'] },
];
