/* =========================================================
   tools/chapters.cjs — the Distributed Systems chapter plan.

   Source for tools/scaffold.cjs, which writes the CHAPTERS
   registry into assets/app.js and creates a placeholder page
   for every chapter that doesn't exist yet. Once a chapter is
   written, assets/app.js is the source of truth for its
   title/blurb; `cover` is only the planned outline.
   DRAFT: the course session reviews this list with the owner
   before writing chapters (docs/course-playbook.md).
   Code is Java (the owner's choice); cross-link System Design's
   Expert level where it covers the same idea at the HLD level.
   ========================================================= */
'use strict';

const P = 'Prerequisites', B = 'Beginner', I = 'Intermediate', A = 'Advanced', E = 'Expert', CS = 'Case Studies';

module.exports = [
  // ---------- Prerequisites ----------
  { n: 0.1, slug: 'p1-java-concurrency', title: 'Java Concurrency Refresher', level: P, icon: '☕', mins: 45,
    blurb: 'Threads, executors, CompletableFuture and the memory model: the single-machine concurrency every node needs.',
    cover: ['Threads and executors', 'CompletableFuture', 'volatile, synchronized and atomics', 'Happens-before'] },
  { n: 0.2, slug: 'p2-rpc-timeouts', title: 'RPC & Timeouts', level: P, icon: '📞', mins: 40,
    blurb: 'A remote call is not a local call: latency, partial failure, and why every call needs a timeout.',
    cover: ['What an RPC is', 'Latency and partial failure', 'Timeouts and deadlines', 'The three outcomes: success, failure, unknown'] },
  { n: 0.3, slug: 'p3-serialization', title: 'Serialization: JSON & Protobuf', level: P, icon: '📦', mins: 35,
    blurb: 'Turning objects into bytes, schema evolution, and why field numbers matter.',
    cover: ['JSON trade-offs', 'Protobuf encoding', 'Backward and forward compatibility', 'Schema evolution rules'] },
  { n: 0.4, slug: 'p4-failure-arithmetic', title: 'Failure Arithmetic: Nines & MTBF', level: P, icon: '🎲', mins: 35,
    blurb: 'Availability as nines, independent vs correlated failures, and why more machines fail more often.',
    cover: ['Nines and downtime budgets', 'Series vs parallel availability', 'MTBF and MTTR', 'Correlated failures'] },
  { n: 0.5, slug: 'p5-clocks-on-one-machine', title: 'Clocks on One Machine', level: P, icon: '🕰️', mins: 30,
    blurb: 'Wall-clock vs monotonic time, clock jumps, and why System.currentTimeMillis lies.',
    cover: ['Wall clock vs monotonic clock', 'NTP adjustments and jumps', 'Leap seconds', 'Measuring durations correctly'] },
  { n: 0.6, slug: 'p6-hashing', title: 'Hashing for Distribution', level: P, icon: '#️⃣', mins: 35,
    blurb: 'Hash functions, uniformity, modulo placement and why adding a node reshuffles everything.',
    cover: ['Good hash functions', 'hash mod N', 'The reshuffle problem', 'A preview of consistent hashing'] },
  { n: 0.7, slug: 'p7-reading-papers', title: 'How to Read a Systems Paper', level: P, icon: '📜', mins: 30,
    blurb: 'A three-pass method for the Dynamo, Raft and Spanner papers this course leans on.',
    cover: ['The three-pass method', 'Finding the system model', 'Reading proofs lightly', 'The papers in this course'] },
  { n: 0.8, slug: 'p8-building-blocks-recap', title: 'System Design Building Blocks, Recapped', level: P, icon: '🧱', mins: 35,
    blurb: 'Load balancers, caches, queues and databases, recapped from System Design so this course can go deeper.',
    cover: ['The building blocks', 'Where state lives', 'What this course adds', 'Links to System Design chapters'] },

  // ---------- Beginner ----------
  { n: 1, slug: '01-why-distributed-is-hard', title: 'Why Distributed Is Hard: The Eight Fallacies', level: B, icon: '🧨', mins: 40,
    blurb: 'The network is not reliable, latency is not zero, and six more assumptions that break systems.',
    cover: ['The eight fallacies', 'Partial failure', 'No global clock', 'What a distributed-systems interview asks'] },
  { n: 2, slug: '02-system-models', title: 'System Models', level: B, icon: '🧩', mins: 40,
    blurb: 'Synchronous, asynchronous and partially synchronous; crash-stop, crash-recovery and Byzantine faults.',
    cover: ['Timing models', 'Failure models', 'Why the model decides what\'s possible', 'The model real systems assume'] },
  { n: 3, slug: '03-grpc-java', title: 'RPC in Java with gRPC', level: B, icon: '📡', mins: 50,
    blurb: 'Defining a service in Protobuf, generated stubs, deadlines, streaming and status codes.',
    cover: ['A .proto service', 'Server and client in Java', 'Deadlines and cancellation', 'Streaming', 'Status codes'] },
  { n: 4, slug: '04-retries-idempotency', title: 'Retries, Backoff & Idempotency', level: B, icon: '🔁', mins: 45,
    blurb: 'Exponential backoff with jitter, retry budgets, and idempotency keys so a retry is safe.',
    cover: ['When to retry', 'Exponential backoff and jitter', 'Retry storms and budgets', 'Idempotency keys', 'At-least-once delivery'] },
  { n: 5, slug: '05-failure-detectors', title: 'Failure Detectors & Heartbeats', level: B, icon: '💓', mins: 40,
    blurb: 'Heartbeats, timeouts, the phi accrual detector, and why you can\'t tell slow from dead.',
    cover: ['Heartbeats', 'Choosing a timeout', 'Phi accrual', 'SWIM-style probing', 'False positives'] },
  { n: 6, slug: '06-ntp-clock-skew', title: 'Physical Clocks, NTP & Skew', level: B, icon: '⏰', mins: 40,
    blurb: 'How NTP synchronises clocks, how far apart they drift, and the bugs skew causes.',
    cover: ['Clock drift', 'How NTP works', 'Skew bounds', 'Last-write-wins and skew', 'PTP'] },
  { n: 7, slug: '07-lamport-clocks', title: 'Lamport Clocks & Happens-Before', level: B, icon: '🔢', mins: 45,
    blurb: 'Ordering events without synchronised clocks: the happens-before relation and logical timestamps.',
    cover: ['Happens-before', 'Lamport timestamps', 'Total order with tie-breaks', 'What Lamport clocks can\'t tell you'] },
  { n: 8, slug: '08-vector-clocks', title: 'Vector Clocks', level: B, icon: '🧮', mins: 45,
    blurb: 'Detecting concurrent updates: vector clocks, comparison, and version vectors in Dynamo-style stores.',
    cover: ['Vector clock rules', 'Comparing vectors', 'Detecting concurrency', 'Version vectors', 'Hybrid logical clocks'] },
  { n: 9, slug: '09-replication-basics', title: 'Replication Basics', level: B, icon: '🪞', mins: 45,
    blurb: 'Single-leader, multi-leader and leaderless replication, and what each costs.',
    cover: ['Why replicate', 'Single leader', 'Multi-leader', 'Leaderless', 'Sync vs async'] },
  { n: 10, slug: '10-cap-pacelc', title: 'CAP & PACELC', level: B, icon: '⚖️', mins: 45,
    blurb: 'What CAP actually says, why "pick two" is misleading, and the latency trade-off PACELC adds.',
    cover: ['The CAP theorem precisely', 'CP vs AP systems', 'PACELC', 'Classifying real databases'] },

  // ---------- Intermediate ----------
  { n: 11, slug: '11-consistency-models', title: 'Consistency Models', level: I, icon: '📏', mins: 55,
    blurb: 'Linearizable, sequential, causal, read-your-writes and eventual consistency, each with a history you can check.',
    cover: ['Linearizability', 'Sequential consistency', 'Causal consistency', 'Session guarantees', 'Eventual consistency'] },
  { n: 12, slug: '12-quorums', title: 'Quorums', level: I, icon: '🗳️', mins: 45,
    blurb: 'R + W > N, sloppy quorums, hinted handoff and read repair, with a quorum simulator.',
    cover: ['Read and write quorums', 'R + W > N', 'Sloppy quorums and hinted handoff', 'Read repair', 'Quorums are not linearizable'] },
  { n: 13, slug: '13-leader-election', title: 'Leader Election', level: I, icon: '👑', mins: 45,
    blurb: 'Bully and ring algorithms, leases, and why two leaders at once is the real danger.',
    cover: ['Why elect a leader', 'Bully and ring', 'Leases', 'Split brain', 'Fencing'] },
  { n: 14, slug: '14-primary-backup', title: 'Primary–Backup Replication', level: I, icon: '📋', mins: 40,
    blurb: 'Forwarding operations to a backup, failover, and the view-change problem.',
    cover: ['The protocol', 'Failover', 'Views and view changes', 'Chain replication'] },
  { n: 15, slug: '15-state-machine-replication', title: 'State Machine Replication', level: I, icon: '🎰', mins: 45,
    blurb: 'Same log, same order, same state: the idea behind every consensus-based system.',
    cover: ['Deterministic state machines', 'The replicated log', 'Why order is everything', 'Snapshots'] },
  { n: 16, slug: '16-paxos', title: 'Paxos', level: I, icon: '🏛️', mins: 55,
    blurb: 'Single-decree Paxos step by step: proposers, acceptors, prepare and accept, and why it\'s safe.',
    cover: ['Roles', 'Phase 1: prepare/promise', 'Phase 2: accept/accepted', 'Why it\'s safe', 'Multi-Paxos'] },
  { n: 17, slug: '17-raft-election', title: 'Raft I: Terms & Leader Election', level: I, icon: '🗳️', mins: 50,
    blurb: 'Followers, candidates and leaders, terms, randomised timeouts and a Raft election simulator.',
    cover: ['Roles and terms', 'Election timeouts', 'RequestVote', 'Split votes', 'Leader heartbeats'] },
  { n: 18, slug: '18-raft-log-replication', title: 'Raft II: Log Replication & Safety', level: I, icon: '📜', mins: 55,
    blurb: 'AppendEntries, commit index, log matching and why a committed entry is never lost.',
    cover: ['AppendEntries', 'Commit index', 'Log matching', 'Election restriction', 'Membership changes'] },
  { n: 19, slug: '19-consistent-hashing', title: 'Consistent Hashing', level: I, icon: '💍', mins: 45,
    blurb: 'The hash ring, virtual nodes, and how few keys move when a node joins or leaves.',
    cover: ['The ring', 'Virtual nodes', 'Adding and removing nodes', 'Rendezvous hashing', 'Jump hash'] },
  { n: 20, slug: '20-partitioning-rebalancing', title: 'Partitioning & Rebalancing', level: I, icon: '🍕', mins: 45,
    blurb: 'Range vs hash partitions, hot spots, and moving data without downtime.',
    cover: ['Range partitioning', 'Hash partitioning', 'Hot spots', 'Rebalancing strategies', 'Request routing'] },
  { n: 21, slug: '21-two-phase-commit', title: 'Two-Phase Commit', level: I, icon: '🤝', mins: 50,
    blurb: 'Coordinator and participants, prepare and commit, and the blocking problem when the coordinator dies.',
    cover: ['The protocol', 'Failure cases', 'Blocking', 'Three-phase commit', '2PC over Paxos/Raft'] },
  { n: 22, slug: '22-sagas', title: 'Sagas & Compensation', level: I, icon: '🧾', mins: 45,
    blurb: 'Long-running transactions as a series of local steps with compensations, orchestrated or choreographed.',
    cover: ['Why not 2PC across services', 'Compensating actions', 'Orchestration vs choreography', 'The outbox pattern'] },
  { n: 23, slug: '23-gossip', title: 'Gossip Protocols', level: I, icon: '🗣️', mins: 40,
    blurb: 'Epidemic dissemination, membership via gossip, and how fast a rumour spreads.',
    cover: ['Push, pull and push–pull', 'Convergence in O(log n) rounds', 'Membership lists', 'SWIM'] },
  { n: 24, slug: '24-merkle-anti-entropy', title: 'Merkle Trees & Anti-Entropy', level: I, icon: '🌲', mins: 40,
    blurb: 'Finding which replicas differ without comparing everything.',
    cover: ['Hash trees', 'Comparing replicas', 'Anti-entropy repair', 'Merkle trees in Cassandra and Git'] },

  // ---------- Advanced ----------
  { n: 25, slug: '25-crdts', title: 'CRDTs', level: A, icon: '🧬', mins: 55,
    blurb: 'Data types that merge without coordination: counters, sets, registers and sequences.',
    cover: ['State-based vs op-based', 'G-Counter and PN-Counter', 'OR-Set', 'LWW registers', 'Sequence CRDTs for collaboration'] },
  { n: 26, slug: '26-dynamo-eventual-consistency', title: 'Dynamo-Style Eventual Consistency', level: A, icon: '🌀', mins: 45,
    blurb: 'Putting it together: consistent hashing, quorums, vector clocks, hinted handoff and anti-entropy.',
    cover: ['The Dynamo design', 'Conflict resolution', 'Tunable consistency', 'Operational lessons'] },
  { n: 27, slug: '27-distributed-snapshots', title: 'Distributed Snapshots (Chandy–Lamport)', level: A, icon: '📸', mins: 45,
    blurb: 'Recording a consistent global state while the system keeps running.',
    cover: ['Consistent cuts', 'The marker algorithm', 'Channel state', 'Snapshots in Flink'] },
  { n: 28, slug: '28-delivery-semantics', title: 'Delivery Semantics & Exactly-Once', level: A, icon: '📬', mins: 50,
    blurb: 'At-most-once, at-least-once, and what "exactly-once" really means in practice.',
    cover: ['The three semantics', 'Deduplication', 'Idempotent consumers', 'Transactional outbox', 'Exactly-once in Kafka'] },
  { n: 29, slug: '29-kafka-internals', title: 'Distributed Logs: Kafka Internals', level: A, icon: '📚', mins: 55,
    blurb: 'Partitions, the replicated log, ISR, leader epochs, consumer groups and offsets.',
    cover: ['Topics and partitions', 'Replication and ISR', 'acks and durability', 'Consumer groups and rebalancing', 'KRaft'] },
  { n: 30, slug: '30-stream-processing-watermarks', title: 'Stream Processing: Time & Watermarks', level: A, icon: '🌊', mins: 50,
    blurb: 'Event time vs processing time, windows, watermarks and late data.',
    cover: ['Event vs processing time', 'Windows', 'Watermarks', 'Late data', 'State and checkpoints'] },
  { n: 31, slug: '31-coordination-zookeeper-etcd', title: 'Coordination Services: ZooKeeper & etcd', level: A, icon: '🗝️', mins: 45,
    blurb: 'Small, strongly consistent stores for config, locks and leader election, and their recipes.',
    cover: ['What they store', 'Watches', 'Ephemeral nodes and leases', 'Lock and election recipes', 'When not to use them'] },
  { n: 32, slug: '32-leases-fencing', title: 'Leases, Locks & Fencing Tokens', level: A, icon: '🎫', mins: 45,
    blurb: 'Why a distributed lock isn\'t enough on its own, and how fencing tokens make it safe.',
    cover: ['Leases', 'The GC-pause problem', 'Fencing tokens', 'Redlock debate', 'Safe locking in Java'] },
  { n: 33, slug: '33-byzantine-pbft', title: 'Byzantine Fault Tolerance & PBFT', level: A, icon: '🛡️', mins: 50,
    blurb: 'Tolerating nodes that lie: 3f + 1 replicas, PBFT phases and where BFT is used.',
    cover: ['Byzantine faults', 'Why 3f + 1', 'PBFT phases', 'Cost', 'Where BFT is used'] },
  { n: 34, slug: '34-blockchain-consensus', title: 'Blockchain Consensus', level: A, icon: '⛓️', mins: 45,
    blurb: 'Proof of work, proof of stake, and modern BFT chains, compared with classical consensus.',
    cover: ['Nakamoto consensus', 'Proof of stake', 'Finality', 'Tendermint/HotStuff', 'Compared with Raft'] },
  { n: 35, slug: '35-truetime-spanner-clocks', title: 'TrueTime & Clock-Based Consistency', level: A, icon: '⌛', mins: 45,
    blurb: 'Bounded clock uncertainty, commit wait, and external consistency without a central sequencer.',
    cover: ['Uncertainty intervals', 'Commit wait', 'External consistency', 'Hybrid logical clocks in CockroachDB'] },
  { n: 36, slug: '36-distributed-tracing', title: 'Distributed Tracing & Debugging', level: A, icon: '🧵', mins: 45,
    blurb: 'Trace and span IDs, context propagation, sampling, and debugging across services.',
    cover: ['Traces and spans', 'Context propagation', 'Sampling', 'OpenTelemetry in Java', 'Finding the slow hop'] },

  // ---------- Expert ----------
  { n: 37, slug: '37-testing-jepsen-simulation', title: 'Testing: Jepsen & Deterministic Simulation', level: E, icon: '🧪', mins: 50,
    blurb: 'Fault injection, linearizability checkers, and deterministic simulation testing.',
    cover: ['Why unit tests miss it', 'Jepsen', 'Linearizability checking', 'Deterministic simulation', 'Chaos in production'] },
  { n: 38, slug: '38-tla-plus', title: 'Formal Methods: TLA+ in Practice', level: E, icon: '📐', mins: 45,
    blurb: 'Specifying a protocol, model checking it, and the bugs AWS found this way.',
    cover: ['Specs and invariants', 'A small TLA+ spec', 'Model checking', 'Industry use'] },
  { n: 39, slug: '39-impossibility-results', title: 'Impossibility Results: FLP & Friends', level: E, icon: '🚫', mins: 40,
    blurb: 'Why consensus is impossible in a fully asynchronous system, and how real systems get around it.',
    cover: ['FLP', 'Two generals', 'Why Raft still works', 'Other lower bounds'] },
  { n: 40, slug: '40-distributed-interview-playbook', title: 'Distributed Systems Interview Playbook', level: E, icon: '🎤', mins: 40,
    blurb: 'The questions that come up, explaining consensus and consistency clearly, and the traps.',
    cover: ['Question map', 'Explaining Raft in three minutes', 'Consistency questions', 'Failure-scenario questions', 'Trick questions'] },

  // ---------- Case studies ----------
  { n: 41, slug: '41-case-spanner', title: 'Case Study: Google Spanner', level: CS, icon: '🌐', mins: 50,
    blurb: 'Globally distributed SQL: Paxos groups, TrueTime and externally consistent transactions.',
    cover: ['Architecture', 'Paxos groups and splits', 'TrueTime', 'Read-write and read-only transactions'] },
  { n: 42, slug: '42-case-dynamo', title: 'Case Study: Amazon Dynamo & DynamoDB', level: CS, icon: '🛒', mins: 45,
    blurb: 'The 2007 shopping-cart store, and how DynamoDB changed the design.',
    cover: ['The shopping cart', 'The original design', 'DynamoDB\'s changes', 'Lessons'] },
  { n: 43, slug: '43-case-kafka', title: 'Case Study: Apache Kafka', level: CS, icon: '📚', mins: 45,
    blurb: 'The log as the backbone: replication, ZooKeeper to KRaft, and exactly-once pipelines.',
    cover: ['The log abstraction', 'Replication', 'From ZooKeeper to KRaft', 'Exactly-once pipelines'] },
  { n: 44, slug: '44-case-etcd-kubernetes', title: 'Case Study: etcd & Kubernetes', level: CS, icon: '☸️', mins: 45,
    blurb: 'Raft in production: how Kubernetes keeps its entire state in etcd, and what happens when etcd struggles.',
    cover: ['etcd\'s Raft', 'The Kubernetes watch model', 'Compaction and defrag', 'Failure scenarios'] },
  { n: 45, slug: '45-case-cassandra', title: 'Case Study: Apache Cassandra', level: CS, icon: '👁️', mins: 45,
    blurb: 'Leaderless replication, tunable consistency, LSM storage and repair.',
    cover: ['The ring', 'Consistency levels', 'Write and read paths', 'Repair and tombstones'] },
  { n: 46, slug: '46-case-gfs-hdfs', title: 'Case Study: GFS & HDFS', level: CS, icon: '🗄️', mins: 45,
    blurb: 'A single master, chunk servers, replication and the append-heavy design.',
    cover: ['Master and chunkservers', 'Chunks and replicas', 'Record append', 'The single-master bottleneck'] },
  { n: 47, slug: '47-case-mapreduce-spark', title: 'Case Study: MapReduce to Spark', level: CS, icon: '🔥', mins: 45,
    blurb: 'Batch processing at scale: map, shuffle, reduce, and Spark\'s in-memory lineage.',
    cover: ['MapReduce', 'The shuffle', 'Stragglers', 'Spark RDDs and lineage', 'From batch to streaming'] },
  { n: 48, slug: '48-case-jepsen-split-brain', title: 'Case Study: A Jepsen Split-Brain Report', level: CS, icon: '🧠', mins: 40,
    blurb: 'How a partition exposed lost writes in a real database, and what the fix looked like.',
    cover: ['The test', 'The partition', 'The anomaly', 'Root cause', 'The fix'] },
];

module.exports.levels = {
  Prerequisites: 'Java concurrency, RPCs, serialization, failure arithmetic and the building blocks the course assumes.',
  Beginner: 'Why distribution is hard: system models, retries, failure detection, clocks, replication and CAP.',
  Intermediate: 'Consistency, quorums, leader election, Paxos, Raft, partitioning, 2PC, sagas and gossip.',
  Advanced: 'CRDTs, Dynamo, snapshots, exactly-once, Kafka, streaming, coordination, BFT and TrueTime.',
  Expert: 'Testing with Jepsen, TLA+, impossibility results and the interview playbook.',
  'Case Studies': 'Eight real systems: Spanner, Dynamo, Kafka, etcd, Cassandra, GFS, Spark and a Jepsen report.',
};
