/* =========================================================
   tools/chapters.cjs — the Cloud & DevOps chapter plan.

   Source for tools/scaffold.cjs, which writes the CHAPTERS
   registry into assets/app.js and creates a placeholder page
   for every chapter that doesn't exist yet. Once a chapter is
   written, assets/app.js is the source of truth for its
   title/blurb; `cover` is only the planned outline.
   DRAFT: the course session reviews this list with the owner
   before writing chapters (docs/course-playbook.md).
   Code: Bash, Dockerfile, Kubernetes YAML, Terraform, GitHub Actions.
   ========================================================= */
'use strict';

const P = 'Prerequisites', B = 'Beginner', I = 'Intermediate', A = 'Advanced', E = 'Expert', CS = 'Case Studies';

module.exports = [
  // ---------- Prerequisites ----------
  { n: 0.1, slug: 'p1-linux-command-line', title: 'The Linux Command Line', level: P, icon: '🐧', mins: 40,
    blurb: 'Navigating, inspecting and editing a server from a terminal: the commands every later chapter uses.',
    cover: ['Files and directories', 'grep, less, tail -f', 'Processes: ps, top, kill', 'Permissions and sudo', 'Package managers'] },
  { n: 0.2, slug: 'p2-bash-scripting', title: 'Bash Scripting', level: P, icon: '📜', mins: 45,
    blurb: 'Variables, conditionals, loops, exit codes and set -euo pipefail: scripts that fail loudly.',
    cover: ['Variables and quoting', 'Exit codes and &&', 'Loops and conditionals', 'set -euo pipefail', 'Functions'] },
  { n: 0.3, slug: 'p3-git-workflows', title: 'Git Workflows', level: P, icon: '🌿', mins: 40,
    blurb: 'Branches, merges, rebases and pull requests: the unit every pipeline starts from.',
    cover: ['Commits and branches', 'Merge vs rebase', 'Pull requests and review', 'Trunk-based vs GitFlow', 'Tags and releases'] },
  { n: 0.4, slug: 'p4-yaml-json', title: 'YAML & JSON', level: P, icon: '🧾', mins: 30,
    blurb: 'The configuration languages of the cloud, and the YAML traps (Norway, octal, indentation).',
    cover: ['YAML structure', 'Anchors and multi-document files', 'The classic traps', 'JSON and jq'] },
  { n: 0.5, slug: 'p5-networking-for-ops', title: 'Networking for Operations', level: P, icon: '🌐', mins: 40,
    blurb: 'Ports, DNS, TLS and load balancers from an operator\'s point of view.',
    cover: ['Ports and listening sockets', 'DNS records you will edit', 'TLS certificates and expiry', 'curl for debugging'] },
  { n: 0.6, slug: 'p6-systemd-services', title: 'Processes & systemd', level: P, icon: '⚙️', mins: 35,
    blurb: 'Running a service properly: unit files, restarts, logs with journalctl.',
    cover: ['Unit files', 'Restart policies', 'journalctl', 'Environment and secrets in units'] },
  { n: 0.7, slug: 'p7-ssh-keys', title: 'SSH & Keys', level: P, icon: '🔑', mins: 30,
    blurb: 'Key pairs, agents, bastion hosts and why passwords are off on real servers.',
    cover: ['Key pairs', 'ssh-agent and config', 'Bastions and jump hosts', 'Hardening sshd'] },
  { n: 0.8, slug: 'p8-http-apis-curl', title: 'HTTP APIs & curl', level: P, icon: '📞', mins: 30,
    blurb: 'Calling cloud APIs by hand: methods, headers, auth tokens and reading error responses.',
    cover: ['Methods and status codes', 'Headers and auth', 'curl flags you will use', 'Reading API errors'] },

  // ---------- Beginner ----------
  { n: 1, slug: '01-devops-and-sre', title: 'DevOps & SRE', level: B, icon: '🧭', mins: 35,
    blurb: 'What the roles mean, the DORA metrics, and what a DevOps interview asks.',
    cover: ['DevOps as a practice', 'SRE and error budgets', 'DORA metrics', 'What a DevOps interview asks'] },
  { n: 2, slug: '02-cloud-fundamentals', title: 'Cloud Fundamentals: Regions, Zones & Services', level: B, icon: '☁️', mins: 40,
    blurb: 'Regions and availability zones, IaaS vs PaaS vs SaaS, and the shared-responsibility model.',
    cover: ['Regions and AZs', 'IaaS, PaaS, SaaS', 'Shared responsibility', 'Pricing basics'] },
  { n: 3, slug: '03-compute', title: 'Compute: VMs & Autoscaling Groups', level: B, icon: '🖥️', mins: 40,
    blurb: 'Instance types, images, autoscaling groups and spot capacity.',
    cover: ['Instance families', 'Machine images', 'Autoscaling groups', 'Spot and preemptible', 'Launch templates'] },
  { n: 4, slug: '04-storage', title: 'Storage: Block, Object & File', level: B, icon: '🗄️', mins: 40,
    blurb: 'EBS-style volumes, S3-style buckets and shared file systems, and when to use each.',
    cover: ['Block volumes', 'Object storage', 'File storage', 'Durability and cost', 'Lifecycle policies'] },
  { n: 5, slug: '05-vpc-networking', title: 'VPCs, Subnets & Security Groups', level: B, icon: '🧱', mins: 50,
    blurb: 'Designing a VPC: public and private subnets, route tables, NAT gateways and security groups.',
    cover: ['VPC and CIDR', 'Public vs private subnets', 'Route tables, IGW and NAT', 'Security groups vs NACLs', 'Peering and endpoints'] },
  { n: 6, slug: '06-iam', title: 'IAM & Least Privilege', level: B, icon: '🪪', mins: 45,
    blurb: 'Users, roles and policies, evaluating a policy decision, and avoiding wildcard permissions.',
    cover: ['Principals, roles and policies', 'How a policy is evaluated', 'Least privilege', 'Instance and workload identity', 'Common mistakes'] },
  { n: 7, slug: '07-containers-docker', title: 'Containers & Docker', level: B, icon: '🐳', mins: 45,
    blurb: 'Images vs containers, docker run, volumes, networks, and what a container is not.',
    cover: ['Images and containers', 'docker run flags', 'Volumes', 'Container networking', 'Containers vs VMs'] },
  { n: 8, slug: '08-dockerfiles', title: 'Writing Good Dockerfiles', level: B, icon: '📄', mins: 45,
    blurb: 'Layers and caching, multi-stage builds, small base images and non-root users.',
    cover: ['Layers and the build cache', 'Multi-stage builds', 'Base images: distroless, alpine, slim', 'Running as non-root', '.dockerignore'] },
  { n: 9, slug: '09-registries', title: 'Container Registries & Tags', level: B, icon: '🏷️', mins: 30,
    blurb: 'Pushing and pulling images, immutable tags vs latest, and digests.',
    cover: ['Registries', 'Tags vs digests', 'Why not :latest', 'Image scanning'] },
  { n: 10, slug: '10-ci-github-actions', title: 'Continuous Integration with GitHub Actions', level: B, icon: '🔁', mins: 50,
    blurb: 'Workflows, jobs, steps, caching and matrix builds: a pipeline that tests every pull request.',
    cover: ['Workflows and triggers', 'Jobs and steps', 'Caching dependencies', 'Matrix builds', 'Secrets in CI'] },

  // ---------- Intermediate ----------
  { n: 11, slug: '11-kubernetes-architecture', title: 'Kubernetes Architecture', level: I, icon: '☸️', mins: 50,
    blurb: 'Control plane and nodes, the API server, etcd, scheduler and controllers, and the reconcile loop.',
    cover: ['Control plane components', 'Nodes and the kubelet', 'Desired state and reconciliation', 'The API and kubectl'] },
  { n: 12, slug: '12-pods-deployments-services', title: 'Pods, Deployments & Services', level: I, icon: '📦', mins: 55,
    blurb: 'The three objects you use every day: pods, deployments with rolling updates, and services.',
    cover: ['Pods', 'ReplicaSets and Deployments', 'Rolling updates and rollbacks', 'Services and endpoints', 'Probes'] },
  { n: 13, slug: '13-config-secrets', title: 'ConfigMaps & Secrets', level: I, icon: '🔐', mins: 40,
    blurb: 'Injecting configuration and secrets, and why a Kubernetes Secret is not encrypted by default.',
    cover: ['ConfigMaps', 'Secrets and base64', 'Env vars vs mounted files', 'External secret stores'] },
  { n: 14, slug: '14-ingress', title: 'Ingress & Load Balancing', level: I, icon: '🚪', mins: 40,
    blurb: 'Getting traffic into the cluster: LoadBalancer services, ingress controllers and the Gateway API.',
    cover: ['NodePort and LoadBalancer', 'Ingress controllers', 'TLS with cert-manager', 'The Gateway API'] },
  { n: 15, slug: '15-kubernetes-storage', title: 'Storage in Kubernetes', level: I, icon: '💾', mins: 40,
    blurb: 'Volumes, PersistentVolumeClaims, storage classes and StatefulSets.',
    cover: ['Volumes', 'PVs and PVCs', 'Storage classes', 'StatefulSets'] },
  { n: 16, slug: '16-helm-kustomize', title: 'Helm & Kustomize', level: I, icon: '⛵', mins: 40,
    blurb: 'Packaging and templating manifests, values files, and overlays per environment.',
    cover: ['Why templating', 'Helm charts and values', 'Kustomize overlays', 'Choosing'] },
  { n: 17, slug: '17-deployment-strategies', title: 'Deployment Strategies: Rolling, Blue-Green & Canary', level: I, icon: '🐤', mins: 50,
    blurb: 'Releasing safely, with a canary simulator: traffic splits, automated analysis and rollback.',
    cover: ['Recreate and rolling', 'Blue-green', 'Canary', 'Feature flags', 'Automated rollback'] },
  { n: 18, slug: '18-gitops-argo', title: 'GitOps with Argo CD', level: I, icon: '🐙', mins: 45,
    blurb: 'Git as the source of truth: pull-based deploys, drift detection and promotions.',
    cover: ['Push vs pull deploys', 'Argo CD applications', 'Sync and drift', 'Promotion between environments'] },
  { n: 19, slug: '19-terraform-basics', title: 'Infrastructure as Code: Terraform Basics', level: I, icon: '🏗️', mins: 50,
    blurb: 'Providers, resources, plan and apply: describing a VPC and a VM in HCL.',
    cover: ['Declarative infrastructure', 'Providers and resources', 'plan and apply', 'Variables and outputs', 'Dependencies'] },
  { n: 20, slug: '20-terraform-state-modules', title: 'Terraform State, Modules & Teams', level: I, icon: '🧱', mins: 50,
    blurb: 'Remote state and locking, modules, workspaces, and running Terraform safely in CI.',
    cover: ['State and why it matters', 'Remote backends and locking', 'Modules', 'Environments', 'Terraform in CI'] },
  { n: 21, slug: '21-metrics-prometheus', title: 'Metrics with Prometheus', level: I, icon: '📈', mins: 50,
    blurb: 'Counters, gauges and histograms, scraping, PromQL, and the RED and USE methods.',
    cover: ['Metric types', 'Scraping and exporters', 'PromQL basics', 'RED and USE', 'Cardinality'] },
  { n: 22, slug: '22-logging', title: 'Logging at Scale', level: I, icon: '🪵', mins: 40,
    blurb: 'Structured logs, shipping and indexing, retention, and logs vs metrics.',
    cover: ['Structured logging', 'Collectors and pipelines', 'Indexing and search', 'Retention and cost'] },
  { n: 23, slug: '23-tracing-opentelemetry', title: 'Tracing with OpenTelemetry', level: I, icon: '🧵', mins: 40,
    blurb: 'Spans across services, the OpenTelemetry collector, and sampling.',
    cover: ['Traces and spans', 'Instrumentation', 'The collector', 'Sampling strategies'] },
  { n: 24, slug: '24-slos-alerting', title: 'SLOs, Error Budgets & Alerting', level: I, icon: '🎯', mins: 50,
    blurb: 'Choosing SLIs, setting SLOs, burn-rate alerts and alerts that don\'t wake you for nothing.',
    cover: ['SLIs and SLOs', 'Error budgets', 'Burn-rate alerts', 'Alert fatigue', 'Paging vs tickets'] },

  // ---------- Advanced ----------
  { n: 25, slug: '25-autoscaling', title: 'Autoscaling: HPA, VPA & Cluster Autoscaler', level: A, icon: '📏', mins: 45,
    blurb: 'Scaling pods and nodes on real signals, and the lag that makes naive autoscaling fail.',
    cover: ['HPA on CPU and custom metrics', 'VPA', 'Cluster autoscaler and Karpenter', 'Scaling lag', 'KEDA'] },
  { n: 26, slug: '26-serverless', title: 'Serverless & Cold Starts', level: A, icon: '⚡', mins: 45,
    blurb: 'Functions as a service, cold starts, concurrency limits and when serverless is cheaper.',
    cover: ['The execution model', 'Cold starts', 'Concurrency limits', 'Cost crossover', 'Event sources'] },
  { n: 27, slug: '27-operating-a-mesh', title: 'Operating a Service Mesh', level: A, icon: '🕸️', mins: 40,
    blurb: 'Rolling out a mesh, mTLS by default, traffic policies and the operational cost.',
    cover: ['Why a mesh', 'mTLS rollout', 'Traffic policies', 'Debugging through sidecars', 'Cost'] },
  { n: 28, slug: '28-secrets-vault-kms', title: 'Secrets Management: Vault & KMS', level: A, icon: '🗝️', mins: 45,
    blurb: 'Dynamic secrets, envelope encryption with KMS, rotation and keeping secrets out of Git.',
    cover: ['Where secrets leak', 'Vault and dynamic secrets', 'KMS and envelope encryption', 'Rotation', 'Secret scanning'] },
  { n: 29, slug: '29-supply-chain-security', title: 'Supply-Chain Security', level: A, icon: '🔗', mins: 45,
    blurb: 'SBOMs, image signing with Sigstore, pinned dependencies and SLSA levels.',
    cover: ['The attack surface', 'SBOMs', 'Signing and verification', 'Pinning actions and images', 'SLSA'] },
  { n: 30, slug: '30-landing-zones', title: 'Multi-Account Landing Zones', level: A, icon: '🗺️', mins: 40,
    blurb: 'Organising cloud accounts, guardrails and centralised logging.',
    cover: ['Why many accounts', 'Organisations and OUs', 'Guardrails (SCPs)', 'Central logging and security'] },
  { n: 31, slug: '31-finops', title: 'FinOps: Cloud Cost Management', level: A, icon: '💸', mins: 40,
    blurb: 'Where the bill comes from, tagging, rightsizing, commitments and egress traps.',
    cover: ['Reading the bill', 'Tagging and allocation', 'Rightsizing', 'Savings plans and reservations', 'Egress costs'] },
  { n: 32, slug: '32-disaster-recovery', title: 'Disaster Recovery: RPO & RTO', level: A, icon: '🆘', mins: 45,
    blurb: 'Backup and restore, pilot light, warm standby and active–active, with their RPO/RTO costs.',
    cover: ['RPO and RTO', 'Backup and restore', 'Pilot light and warm standby', 'Active–active', 'DR drills'] },
  { n: 33, slug: '33-multi-region', title: 'Multi-Region Deployments', level: A, icon: '🌍', mins: 45,
    blurb: 'Routing users to regions, data replication choices, and failing over a whole region.',
    cover: ['Why multi-region', 'Global load balancing', 'Data replication', 'Regional failover', 'Cell-based architecture'] },
  { n: 34, slug: '34-chaos-engineering', title: 'Chaos Engineering', level: A, icon: '🐒', mins: 40,
    blurb: 'Hypothesis-driven failure experiments, blast radius, and game days.',
    cover: ['The method', 'Blast radius', 'Tools', 'Game days'] },
  { n: 35, slug: '35-platform-engineering', title: 'Platform Engineering & Developer Platforms', level: A, icon: '🛠️', mins: 40,
    blurb: 'Golden paths, self-service templates, and treating the platform as a product.',
    cover: ['Why platform teams', 'Golden paths', 'Backstage and templates', 'Measuring the platform'] },
  { n: 36, slug: '36-policy-as-code', title: 'Policy as Code: OPA & Admission Control', level: A, icon: '📜', mins: 40,
    blurb: 'Enforcing rules automatically: OPA/Rego, Kyverno and admission webhooks.',
    cover: ['Why policy as code', 'OPA and Rego', 'Admission controllers', 'Kyverno', 'Policies in CI'] },

  // ---------- Expert ----------
  { n: 37, slug: '37-incident-response', title: 'Incident Response & Postmortems', level: E, icon: '🚨', mins: 45,
    blurb: 'Severity, roles, communication, mitigation first, and blameless postmortems.',
    cover: ['Severity levels', 'Incident roles', 'Mitigate, then diagnose', 'Communication', 'Blameless postmortems'] },
  { n: 38, slug: '38-on-call-toil', title: 'On-Call & Toil Reduction', level: E, icon: '📟', mins: 40,
    blurb: 'Healthy rotations, runbooks, measuring toil and automating it away.',
    cover: ['Rotations', 'Runbooks', 'Toil defined', 'Automation priorities'] },
  { n: 39, slug: '39-capacity-planning', title: 'Capacity Planning', level: E, icon: '📊', mins: 40,
    blurb: 'Forecasting demand, headroom, load testing and the cost of being wrong.',
    cover: ['Demand forecasting', 'Headroom', 'Load testing', 'Organic vs event-driven growth'] },
  { n: 40, slug: '40-devops-interview-playbook', title: 'DevOps & SRE Interview Playbook', level: E, icon: '🎤', mins: 40,
    blurb: 'The questions that come up, troubleshooting scenarios, and the traps.',
    cover: ['Question map', 'Troubleshooting walkthroughs', 'Kubernetes questions', 'Incident questions', 'Trick questions'] },

  // ---------- Case studies ----------
  { n: 41, slug: '41-case-laptop-to-production', title: 'Case Study: From Laptop to Production', level: CS, icon: '🚀', mins: 55,
    blurb: 'One web service through Dockerfile, CI, registry, Terraform, Kubernetes, monitoring and a canary release.',
    cover: ['The service', 'Build and CI', 'Infrastructure', 'Deploy and canary', 'Monitoring and alerts'] },
  { n: 42, slug: '42-case-zero-downtime-migration', title: 'Case Study: A Zero-Downtime Database Migration', level: CS, icon: '🔀', mins: 45,
    blurb: 'Moving a live service to a new database with dual writes, backfill, verification and cutover.',
    cover: ['The plan', 'Dual writes', 'Backfill and verification', 'Cutover and rollback plan'] },
  { n: 43, slug: '43-case-kubernetes-outage', title: 'Case Study: A Kubernetes Outage', level: CS, icon: '💥', mins: 40,
    blurb: 'A misconfigured change cascades through a cluster: the timeline, the root cause and the fixes.',
    cover: ['The change', 'The cascade', 'Diagnosis', 'Recovery', 'Guardrails added'] },
  { n: 44, slug: '44-case-aws-us-east-1-2021', title: 'Case Study: AWS us-east-1, December 2021', level: CS, icon: '☁️', mins: 40,
    blurb: 'An internal network overload that took down services far beyond one region\'s customers.',
    cover: ['What failed', 'Why it spread', 'Control plane vs data plane', 'Lessons for your architecture'] },
  { n: 45, slug: '45-case-crowdstrike-2024', title: 'Case Study: CrowdStrike 2024 & Staged Rollouts', level: CS, icon: '🟦', mins: 40,
    blurb: 'A content update crashed millions of Windows machines at once: why staged rollouts exist.',
    cover: ['The update', 'Why every machine crashed', 'Recovery at scale', 'Staged rollout principles'] },
  { n: 46, slug: '46-case-cloud-cost-blowout', title: 'Case Study: A Cloud-Cost Blowout', level: CS, icon: '🔥', mins: 35,
    blurb: 'A runaway bill from a logging loop and cross-region egress, found and fixed.',
    cover: ['The bill', 'Finding the cause', 'Egress and logging traps', 'Budgets and anomaly alerts'] },
  { n: 47, slug: '47-case-monolith-to-kubernetes', title: 'Case Study: Moving a Monolith to Kubernetes', level: CS, icon: '🏗️', mins: 45,
    blurb: 'Containerising a legacy app, strangler routing, and what changed operationally.',
    cover: ['The starting point', 'Containerising', 'Strangler fig routing', 'Operational changes', 'What went wrong'] },
  { n: 48, slug: '48-case-actions-supply-chain', title: 'Case Study: The 2025 GitHub Actions Supply-Chain Attack', level: CS, icon: '🕵️', mins: 40,
    blurb: 'A compromised action leaked CI secrets across thousands of repositories: pinning, least privilege and detection.',
    cover: ['The compromise', 'How secrets leaked', 'Blast radius', 'Pinning by SHA', 'Least-privilege tokens'] },
];

module.exports.levels = {
  Prerequisites: 'The Linux shell, Bash, Git, YAML, networking and the tools the course assumes.',
  Beginner: 'Cloud basics, networking, IAM, containers, Dockerfiles and continuous integration.',
  Intermediate: 'Kubernetes, deployment strategies, GitOps, Terraform, observability and SLOs.',
  Advanced: 'Autoscaling, serverless, secrets, supply chain, cost, disaster recovery, multi-region and platforms.',
  Expert: 'Incidents, on-call, capacity planning and the interview playbook.',
  'Case Studies': 'Eight real deployments and outages, from laptop to production to CrowdStrike.',
};
