/* =========================================================
   tools/chapters.cjs — the Database Internals & SQL chapter plan.

   Source for tools/scaffold.cjs, which writes the CHAPTERS
   registry into assets/app.js and creates a placeholder page
   for every chapter that doesn't exist yet. Once a chapter is
   written, assets/app.js is the source of truth for its
   title/blurb; `cover` is only the planned outline.
   DRAFT: the course session reviews this list with the owner
   before writing chapters (docs/course-playbook.md).
   ========================================================= */
'use strict';

const P = 'Prerequisites', B = 'Beginner', I = 'Intermediate', A = 'Advanced', E = 'Expert', CS = 'Case Studies';

module.exports = [
  // ---------- Prerequisites ----------
  { n: 0.1, slug: 'p1-tables-and-keys', title: 'Tables, Rows & Keys', level: P, icon: '🗃️', mins: 35,
    blurb: 'Tables as sets of rows, primary keys, foreign keys, and why every row needs an identity.',
    cover: ['Rows and columns', 'Primary keys', 'Foreign keys', 'Natural vs surrogate keys'] },
  { n: 0.2, slug: 'p2-first-select', title: 'Your First SELECT', level: P, icon: '🔎', mins: 40,
    blurb: 'SELECT, WHERE, ORDER BY and LIMIT against a real PostgreSQL database.',
    cover: ['psql and a sample database', 'SELECT and WHERE', 'ORDER BY and LIMIT', 'NULL and three-valued logic'] },
  { n: 0.3, slug: 'p3-disks-and-files', title: 'Disks, Files & Pages', level: P, icon: '💽', mins: 35,
    blurb: 'Why databases read in pages, SSD vs HDD, and sequential vs random I/O.',
    cover: ['Block devices and pages', 'HDD seeks vs SSD', 'Sequential vs random I/O', 'The OS page cache'] },
  { n: 0.4, slug: 'p4-data-types', title: 'Data Types', level: P, icon: '🔤', mins: 35,
    blurb: 'Integers, numeric, text, timestamps with time zones, JSON, and choosing the right one.',
    cover: ['Integer and numeric types', 'text vs varchar', 'timestamp vs timestamptz', 'JSON and JSONB', 'Choosing types for size and correctness'] },
  { n: 0.5, slug: 'p5-json-csv', title: 'JSON, CSV & Loading Data', level: P, icon: '📥', mins: 30,
    blurb: 'Getting data in and out: COPY, CSV quirks and JSON documents.',
    cover: ['COPY FROM and COPY TO', 'CSV quoting traps', 'JSON documents', 'Bulk loading'] },
  { n: 0.6, slug: 'p6-python-psycopg', title: 'Python & psycopg', level: P, icon: '🐍', mins: 40,
    blurb: 'Querying from Python, parameters vs string formatting, and transactions from application code.',
    cover: ['Connecting', 'Parameterised queries (and SQL injection)', 'Fetching results', 'Transactions and autocommit'] },
  { n: 0.7, slug: 'p7-sets-relational-algebra', title: 'Sets & Relational Algebra', level: P, icon: '∩', mins: 35,
    blurb: 'Selection, projection, join and union: the algebra every SQL query becomes.',
    cover: ['Relations as sets', 'Selection and projection', 'Joins as products plus filters', 'Union, intersection, difference'] },
  { n: 0.8, slug: 'p8-data-size-math', title: 'Data-Size Arithmetic', level: P, icon: '🧮', mins: 30,
    blurb: 'Row sizes, table sizes and index sizes, estimated before you build anything.',
    cover: ['Bytes per row', 'Rows per page', 'Table and index size estimates', 'Growth over time'] },

  // ---------- Beginner ----------
  { n: 1, slug: '01-relational-model', title: 'The Relational Model', level: B, icon: '🏛️', mins: 35,
    blurb: 'Why relations, why declarative queries, and what a database interview asks.',
    cover: ['Codd\'s idea', 'Declarative vs imperative', 'Schema and instances', 'What a database interview asks'] },
  { n: 2, slug: '02-filtering-sorting', title: 'Filtering, Sorting & Pagination', level: B, icon: '🧹', mins: 40,
    blurb: 'Predicates, LIKE and ILIKE, ORDER BY, and why OFFSET pagination gets slow.',
    cover: ['Comparison and pattern predicates', 'IN and BETWEEN', 'ORDER BY with ties', 'OFFSET vs keyset pagination'] },
  { n: 3, slug: '03-joins', title: 'Joins', level: B, icon: '🔗', mins: 50,
    blurb: 'Inner, left, right, full and cross joins, with a join visualiser, and the duplicate-rows trap.',
    cover: ['Inner join', 'Outer joins', 'Self joins', 'Cross joins', 'Fan-out and duplicate rows'] },
  { n: 4, slug: '04-group-by-aggregates', title: 'GROUP BY & Aggregates', level: B, icon: '📊', mins: 45,
    blurb: 'COUNT, SUM, AVG, HAVING, and the "must appear in GROUP BY" error explained.',
    cover: ['Aggregate functions', 'GROUP BY', 'HAVING vs WHERE', 'COUNT(*) vs COUNT(col)', 'GROUPING SETS'] },
  { n: 5, slug: '05-subqueries-ctes', title: 'Subqueries & CTEs', level: B, icon: '🪆', mins: 45,
    blurb: 'Scalar, correlated and EXISTS subqueries, WITH clauses, and recursive CTEs for trees.',
    cover: ['Scalar and IN subqueries', 'Correlated subqueries and EXISTS', 'WITH (CTEs)', 'Recursive CTEs'] },
  { n: 6, slug: '06-window-functions', title: 'Window Functions', level: B, icon: '🪟', mins: 50,
    blurb: 'ROW_NUMBER, RANK, running totals and LAG/LEAD: the most-asked advanced SQL in interviews.',
    cover: ['OVER and PARTITION BY', 'ROW_NUMBER, RANK, DENSE_RANK', 'Running totals and frames', 'LAG and LEAD', 'Top-N per group'] },
  { n: 7, slug: '07-normalization', title: 'Schema Design & Normalisation', level: B, icon: '📐', mins: 50,
    blurb: 'Anomalies, 1NF to BCNF with a worked example, and when to denormalise on purpose.',
    cover: ['Update, insert and delete anomalies', 'Functional dependencies', '1NF, 2NF, 3NF, BCNF', 'Denormalising deliberately'] },
  { n: 8, slug: '08-constraints-integrity', title: 'Constraints & Integrity', level: B, icon: '🛡️', mins: 40,
    blurb: 'NOT NULL, UNIQUE, CHECK, foreign keys and cascades: letting the database enforce the rules.',
    cover: ['Keys and uniqueness', 'Foreign keys and ON DELETE', 'CHECK constraints', 'Deferrable constraints', 'Exclusion constraints'] },
  { n: 9, slug: '09-indexes-first-look', title: 'Indexes: A First Look', level: B, icon: '📇', mins: 45,
    blurb: 'Why an index makes a lookup fast, what it costs on writes, and which columns deserve one.',
    cover: ['Full scan vs index lookup', 'Selectivity', 'Composite indexes and column order', 'The write cost', 'Covering indexes'] },
  { n: 10, slug: '10-transactions-acid', title: 'Transactions & ACID', level: B, icon: '💳', mins: 45,
    blurb: 'BEGIN, COMMIT, ROLLBACK, and what atomicity, consistency, isolation and durability each promise.',
    cover: ['BEGIN, COMMIT, ROLLBACK', 'Atomicity', 'Consistency', 'Isolation (a preview)', 'Durability'] },

  // ---------- Intermediate ----------
  { n: 11, slug: '11-pages-heap-files', title: 'Pages, Tuples & Heap Files', level: I, icon: '📄', mins: 45,
    blurb: 'How a row is laid out on an 8 KB page, slotted pages, TOAST and the heap file.',
    cover: ['Slotted pages', 'Tuple headers', 'Heap files', 'TOAST for large values', 'Fillfactor'] },
  { n: 12, slug: '12-buffer-pool', title: 'The Buffer Pool', level: I, icon: '🏊', mins: 45,
    blurb: 'Caching pages in memory, pinning, dirty pages and eviction, with a buffer-pool simulator.',
    cover: ['Why a buffer pool', 'Pin counts and dirty flags', 'Eviction: LRU and clock sweep', 'shared_buffers and the OS cache'] },
  { n: 13, slug: '13-b-trees', title: 'B-Trees', level: I, icon: '🌳', mins: 55,
    blurb: 'The index behind almost every database: search, insert, page splits and range scans.',
    cover: ['Why a wide, shallow tree', 'Search', 'Insert and page splits', 'Range scans', 'B+ trees'] },
  { n: 14, slug: '14-lsm-trees', title: 'LSM Trees', level: I, icon: '🪜', mins: 50,
    blurb: 'Memtables, SSTables, compaction and bloom filters: the write-optimised design behind RocksDB and Cassandra.',
    cover: ['Memtable and WAL', 'SSTables', 'Compaction strategies', 'Bloom filters', 'Read, write and space amplification'] },
  { n: 15, slug: '15-other-indexes', title: 'Hash, GIN, GiST & Bitmap Indexes', level: I, icon: '🗂️', mins: 45,
    blurb: 'When a B-tree isn\'t the right shape: hash, inverted (GIN), GiST, BRIN and bitmap indexes.',
    cover: ['Hash indexes', 'GIN for arrays, JSONB and text', 'GiST for ranges and geometry', 'BRIN', 'Bitmap scans'] },
  { n: 16, slug: '16-query-processing', title: 'How a Query Runs', level: I, icon: '⚙️', mins: 45,
    blurb: 'Parse, rewrite, plan, execute: the Volcano iterator model and a query traced end to end.',
    cover: ['Parse and analyse', 'Rewrite', 'Plan', 'Execute: the iterator model', 'Vectorised execution'] },
  { n: 17, slug: '17-explain', title: 'Reading EXPLAIN', level: I, icon: '🔬', mins: 50,
    blurb: 'Plan nodes, estimated vs actual rows, costs and buffers, and spotting the bad node.',
    cover: ['EXPLAIN vs EXPLAIN ANALYZE', 'Scan and join nodes', 'Estimated vs actual rows', 'Buffers', 'A checklist for slow plans'] },
  { n: 18, slug: '18-join-algorithms', title: 'Join Algorithms', level: I, icon: '🔀', mins: 50,
    blurb: 'Nested loop, hash join and merge join, and when the planner picks each.',
    cover: ['Nested loop (and index nested loop)', 'Hash join', 'Merge join', 'Costs compared', 'Join order'] },
  { n: 19, slug: '19-cost-based-optimizer', title: 'The Cost-Based Optimiser', level: I, icon: '🧠', mins: 45,
    blurb: 'Statistics, selectivity estimates, and why a stale estimate produces a terrible plan.',
    cover: ['Statistics and ANALYZE', 'Selectivity estimation', 'Correlated columns', 'Join ordering', 'When to override the planner'] },
  { n: 20, slug: '20-wal-recovery', title: 'WAL & Crash Recovery', level: I, icon: '📓', mins: 50,
    blurb: 'Write-ahead logging, checkpoints and replaying the log after a crash (ARIES in one picture).',
    cover: ['Why write-ahead', 'Log records and LSNs', 'Checkpoints', 'Redo and undo', 'full_page_writes'] },
  { n: 21, slug: '21-isolation-anomalies', title: 'Isolation Levels & Anomalies', level: I, icon: '🧪', mins: 55,
    blurb: 'Dirty reads, non-repeatable reads, phantoms, lost updates and write skew, each reproduced.',
    cover: ['The anomalies', 'Read committed', 'Repeatable read / snapshot', 'Serializable', 'Write skew'] },
  { n: 22, slug: '22-two-phase-locking', title: 'Locking & Two-Phase Locking', level: I, icon: '🔒', mins: 45,
    blurb: 'Shared and exclusive locks, 2PL and strict 2PL, row locks and SELECT FOR UPDATE.',
    cover: ['Shared vs exclusive', 'Two-phase locking', 'Row and table locks', 'SELECT … FOR UPDATE', 'Lock escalation'] },
  { n: 23, slug: '23-mvcc', title: 'MVCC: Many Versions, No Read Locks', level: I, icon: '🧬', mins: 55,
    blurb: 'How PostgreSQL and MySQL keep old row versions so readers never block writers, and VACUUM.',
    cover: ['Row versions and xmin/xmax', 'Snapshots', 'Postgres vs MySQL undo logs', 'VACUUM and bloat', 'Transaction ID wraparound'] },
  { n: 24, slug: '24-db-deadlocks', title: 'Deadlocks in Databases', level: I, icon: '🪢', mins: 40,
    blurb: 'How two transactions deadlock, how the database detects it, and how to write code that doesn\'t.',
    cover: ['A deadlock reproduced', 'Wait-for graphs and detection', 'Lock ordering', 'Retries', 'lock_timeout'] },

  // ---------- Advanced ----------
  { n: 25, slug: '25-replication', title: 'Replication', level: A, icon: '🪞', mins: 50,
    blurb: 'Physical vs logical, synchronous vs asynchronous, replication lag and failover.',
    cover: ['Streaming (physical) replication', 'Logical replication', 'Sync vs async', 'Replication lag', 'Failover and split brain'] },
  { n: 26, slug: '26-partitioning-sharding', title: 'Partitioning & Sharding', level: A, icon: '🍰', mins: 50,
    blurb: 'Range, list and hash partitions within one database, and sharding across many.',
    cover: ['Declarative partitioning', 'Partition pruning', 'Choosing a shard key', 'Cross-shard queries', 'Resharding'] },
  { n: 27, slug: '27-connection-pooling', title: 'Connection Pooling', level: A, icon: '🔌', mins: 40,
    blurb: 'Why connections are expensive, PgBouncer modes, and sizing a pool.',
    cover: ['The cost of a connection', 'Application pools', 'PgBouncer: session vs transaction', 'Pool sizing'] },
  { n: 28, slug: '28-column-stores-olap', title: 'Column Stores & OLAP', level: A, icon: '🗄️', mins: 50,
    blurb: 'Row vs column layout, compression, vectorised scans, and why analytics warehouses are columnar.',
    cover: ['OLTP vs OLAP', 'Columnar layout', 'Compression and encoding', 'Vectorised execution', 'Star schemas'] },
  { n: 29, slug: '29-time-series', title: 'Time-Series Storage', level: A, icon: '📈', mins: 40,
    blurb: 'Append-heavy data, time partitioning, downsampling and retention.',
    cover: ['Time-series workloads', 'Chunking by time', 'Compression (delta, Gorilla)', 'Downsampling and retention'] },
  { n: 30, slug: '30-nosql-families', title: 'NoSQL Families', level: A, icon: '🧺', mins: 50,
    blurb: 'Key-value, document, wide-column and graph databases: data models and trade-offs.',
    cover: ['Key-value', 'Document', 'Wide-column', 'Graph', 'Choosing'] },
  { n: 31, slug: '31-search-inverted-index', title: 'Search & Inverted Indexes', level: A, icon: '🔍', mins: 45,
    blurb: 'Tokenising, inverted indexes, BM25 ranking, and full-text search in Postgres vs Elasticsearch.',
    cover: ['Tokens and analysers', 'The inverted index', 'TF-IDF and BM25', 'Postgres full-text search', 'Elasticsearch shards'] },
  { n: 32, slug: '32-vector-databases', title: 'Vector Databases', level: A, icon: '🧭', mins: 45,
    blurb: 'Embeddings, nearest-neighbour search, HNSW and IVF indexes, and pgvector.',
    cover: ['Embeddings and distance', 'Exact vs approximate search', 'HNSW', 'IVF and product quantisation', 'pgvector'] },
  { n: 33, slug: '33-caching-materialized-views', title: 'Caching & Materialised Views', level: A, icon: '🧊', mins: 40,
    blurb: 'Precomputing results inside and outside the database, and keeping them fresh.',
    cover: ['Materialised views', 'Refresh strategies', 'Application caches', 'Cache invalidation'] },
  { n: 34, slug: '34-schema-migrations', title: 'Schema Migrations at Scale', level: A, icon: '🛠️', mins: 45,
    blurb: 'Adding columns and indexes without downtime: expand–contract, concurrent indexes and backfills.',
    cover: ['Locks taken by ALTER TABLE', 'CREATE INDEX CONCURRENTLY', 'Expand and contract', 'Backfills', 'Online schema-change tools'] },
  { n: 35, slug: '35-backups-pitr', title: 'Backups & Point-in-Time Recovery', level: A, icon: '⏪', mins: 40,
    blurb: 'Logical vs physical backups, base backups plus WAL archiving, and restoring to a moment.',
    cover: ['pg_dump vs base backups', 'WAL archiving', 'Point-in-time recovery', 'Testing restores'] },
  { n: 36, slug: '36-distributed-sql', title: 'Distributed SQL', level: A, icon: '🌐', mins: 50,
    blurb: 'Spanner, CockroachDB and YugabyteDB: ranges, Raft per range and distributed transactions.',
    cover: ['Ranges and splits', 'Raft per range', 'Distributed transactions', 'Clock skew and TrueTime', 'When to choose distributed SQL'] },

  // ---------- Expert ----------
  { n: 37, slug: '37-tuning-playbook', title: 'Performance Tuning Playbook', level: E, icon: '🔧', mins: 45,
    blurb: 'pg_stat_statements, finding the top queries, fixing them, and the config that matters.',
    cover: ['pg_stat_statements', 'Top queries by total time', 'Index fixes', 'Memory settings', 'Autovacuum tuning'] },
  { n: 38, slug: '38-orms-n-plus-1', title: 'ORMs & the N+1 Problem', level: E, icon: '🔁', mins: 40,
    blurb: 'What ORMs generate, the N+1 query pattern, eager loading, and when to drop to SQL.',
    cover: ['What the ORM runs', 'N+1 explained', 'Eager loading and batching', 'Transactions in ORMs', 'Raw SQL escape hatches'] },
  { n: 39, slug: '39-sql-drills', title: 'SQL Interview Drills', level: E, icon: '🏋️', mins: 50,
    blurb: 'The classic SQL questions: second-highest salary, top-N per group, gaps and islands, running totals.',
    cover: ['Second-highest salary', 'Top-N per group', 'Gaps and islands', 'Running totals', 'Pivoting'] },
  { n: 40, slug: '40-db-interview-playbook', title: 'Database Interview Playbook', level: E, icon: '🎤', mins: 40,
    blurb: 'The questions that come up, how to explain indexes, transactions and MVCC clearly, and the traps.',
    cover: ['Question map by topic', 'Explaining an index in two minutes', 'Isolation questions', 'SQL vs NoSQL done well', 'Trick questions'] },

  // ---------- Case studies ----------
  { n: 41, slug: '41-case-ecommerce-schema', title: 'Case Study: Designing an E-Commerce Schema', level: CS, icon: '🛒', mins: 50,
    blurb: 'Products, variants, carts, orders and inventory: a schema that survives real requirements.',
    cover: ['Entities and relationships', 'Orders as immutable facts', 'Inventory without oversell', 'Indexes for the hot queries'] },
  { n: 42, slug: '42-case-slow-query', title: 'Case Study: A Slow Query Made Fast', level: CS, icon: '🐢', mins: 45,
    blurb: 'From 12 seconds to 4 ms: reading the plan, fixing the estimate, and choosing the right index.',
    cover: ['The symptom', 'The plan', 'The bad estimate', 'The index', 'Verifying under load'] },
  { n: 43, slug: '43-case-uber-postgres-mysql', title: 'Case Study: Uber\'s Move from Postgres to MySQL', level: CS, icon: '🚕', mins: 40,
    blurb: 'Write amplification, replication and MVCC differences, and the arguments on both sides.',
    cover: ['Uber\'s workload', 'Write amplification', 'Replication differences', 'The rebuttals', 'Lessons'] },
  { n: 44, slug: '44-case-github-mysql-failover', title: 'Case Study: GitHub\'s MySQL Failover Incident', level: CS, icon: '🐙', mins: 40,
    blurb: 'A 43-second network partition and a 24-hour recovery: cross-region failover gone wrong.',
    cover: ['The partition', 'Orchestrator\'s failover', 'Writes on both sides', 'The recovery', 'Lessons'] },
  { n: 45, slug: '45-case-discord-messages', title: 'Case Study: Discord\'s Trillions of Messages', level: CS, icon: '💬', mins: 45,
    blurb: 'Partition design on Cassandra, hot partitions and compaction pain, and the move to ScyllaDB.',
    cover: ['The data model', 'Partition keys by channel and bucket', 'Hot partitions', 'Moving to ScyllaDB', 'Data services'] },
  { n: 46, slug: '46-case-instagram-ids', title: 'Case Study: Instagram\'s Sharded IDs', level: CS, icon: '📸', mins: 35,
    blurb: 'Generating sortable 64-bit IDs inside Postgres across thousands of logical shards.',
    cover: ['Why not auto-increment', 'The ID layout', 'Logical shards', 'The PL/pgSQL function'] },
  { n: 47, slug: '47-case-mini-lsm-store', title: 'Case Study: Building a Mini LSM Key-Value Store', level: CS, icon: '🧱', mins: 55,
    blurb: 'A memtable, a WAL, SSTables and compaction in a few hundred lines of Python.',
    cover: ['The API', 'Memtable and WAL', 'Flushing SSTables', 'Reads across levels', 'Compaction'] },
  { n: 48, slug: '48-case-analytics-warehouse', title: 'Case Study: An Analytics Warehouse', level: CS, icon: '🏬', mins: 45,
    blurb: 'Events into a star schema, a columnar warehouse, and dashboards that stay fast.',
    cover: ['Event ingestion', 'Facts and dimensions', 'Partitioning and clustering', 'Materialised rollups'] },
];

module.exports.levels = {
  Prerequisites: 'Tables, keys, basic SQL, disks and the data-size arithmetic the course assumes.',
  Beginner: 'SQL you will actually write: joins, aggregates, window functions, schema design, indexes and transactions.',
  Intermediate: 'What happens underneath: pages, buffer pools, B-trees, LSM trees, query plans, WAL, isolation and MVCC.',
  Advanced: 'Scaling out: replication, sharding, pooling, column stores, NoSQL, search, vectors and migrations.',
  Expert: 'Tuning, ORMs, SQL drills and the interview playbook.',
  'Case Studies': 'Eight real designs and incidents, from an e-commerce schema to GitHub\'s failover.',
};
