/* =========================================================
   tools/chapters.cjs — the OS & Concurrency chapter plan.

   Source for tools/scaffold.cjs, which writes the CHAPTERS
   registry into assets/app.js and creates a placeholder page
   for every chapter that doesn't exist yet. Once a chapter is
   written, assets/app.js is the source of truth for its
   title/blurb; `cover` is only the planned outline.

     see   related chapters in other Atlas courses (cross-links)
   ========================================================= */
'use strict';

const P = 'Prerequisites', B = 'Beginner', I = 'Intermediate', A = 'Advanced', E = 'Expert', CS = 'Case Studies';

module.exports = [
  // ---------- Prerequisites: the C and machine basics the course assumes ----------
  { n: 0.1, slug: 'p1-c-for-systems', title: 'C for Systems: Pointers & Memory', level: P, icon: '🧷', mins: 45,
    blurb: 'Pointers, addresses and the stack vs the heap: the C you need to read systems code without fear.',
    cover: ['Variables live at addresses', 'Pointers, & and *', 'Stack frames vs malloc/free', 'Dangling pointers, leaks and use-after-free', 'Why the OS is written in C'] },
  { n: 0.2, slug: 'p2-structs-arrays-strings', title: 'Structs, Arrays & Strings in C', level: P, icon: '🧱', mins: 40,
    blurb: 'How structs lay out in memory, arrays decay to pointers, and C strings end in a zero byte.',
    cover: ['struct layout, padding and alignment', 'Arrays and pointer arithmetic', 'NUL-terminated strings and buffer overflows', 'Function pointers (how the kernel does "interfaces")'] },
  { n: 0.3, slug: 'p3-how-cpu-runs-code', title: 'How a CPU Runs Your Code', level: P, icon: '⚙️', mins: 40,
    blurb: 'Registers, the program counter and the fetch–decode–execute loop, from a C line to machine instructions.',
    cover: ['Registers and the program counter', 'Fetch, decode, execute', 'The stack pointer and function calls', 'Pipelines and why branches cost', 'Reading a few lines of assembly'] },
  { n: 0.4, slug: 'p4-memory-hierarchy', title: 'The Memory Hierarchy', level: P, icon: '🏔️', mins: 35,
    blurb: 'Registers, caches, RAM, SSD and network: the latency numbers every systems decision rests on.',
    cover: ['Latency numbers (ns to ms)', 'Cache lines and locality', 'Why sequential beats random', 'Throughput vs latency'] },
  { n: 0.5, slug: 'p5-bits-hex-binary', title: 'Bits, Hex & Binary Data', level: P, icon: '🔢', mins: 35,
    blurb: 'Binary and hex, bit masks and shifts, endianness and fixed-width integers, as used in page tables and flags.',
    cover: ['Binary and hex by hand', 'Masks, shifts and flags', 'Signed vs unsigned, overflow', 'Endianness', 'Powers of two: KiB, MiB, 4 KiB pages'] },
  { n: 0.6, slug: 'p6-compiling-linking', title: 'Compiling & Linking', level: P, icon: '🔗', mins: 40,
    blurb: 'Preprocessor, compiler, assembler and linker: how source becomes an ELF executable, and static vs shared libraries.',
    cover: ['The four stages of gcc', 'Object files and symbols', 'Static vs dynamic linking', 'The ELF layout: text, data, bss', 'What happens when a symbol is missing'] },
  { n: 0.7, slug: 'p7-linux-shell-files', title: 'The Linux Shell & Files', level: P, icon: '🐚', mins: 35,
    blurb: 'Paths, permissions, processes and pipes from the user\'s side: what the rest of the course explains from underneath.',
    cover: ['Paths, working directory and the tree', 'Permissions: rwx, owner, group', 'ps, top and kill', 'Pipes and redirection', 'Environment variables'] },
  { n: 0.8, slug: 'p8-syscalls-man-pages', title: 'Reading Syscalls & Man Pages', level: P, icon: '📖', mins: 30,
    blurb: 'man 2 vs man 3, return values and errno, and watching a program\'s system calls with strace.',
    cover: ['Library calls vs system calls', 'Reading a man page', 'Return values and errno', 'strace in five minutes'] },

  // ---------- Beginner ----------
  { n: 1, slug: '01-what-an-os-does', title: 'What an Operating System Does', level: B, icon: '🧭', mins: 35,
    blurb: 'Three jobs: share the hardware, hide its details behind abstractions, and protect programs from each other.',
    cover: ['Virtualising the CPU, memory and storage', 'Abstractions: process, address space, file', 'Protection and isolation', 'Monolithic vs microkernel', 'What an OS interview asks'] },
  { n: 2, slug: '02-kernel-user-mode-syscalls', title: 'Kernel Mode, User Mode & System Calls', level: B, icon: '🛡️', mins: 45,
    blurb: 'Privilege rings, the trap into the kernel, and what really happens when your program calls read().',
    cover: ['Two modes and why', 'The syscall instruction and the trap table', 'A read() from user space to the driver and back', 'Cost of a syscall; vDSO', 'Exceptions and faults'] },
  { n: 3, slug: '03-processes-fork-exec-wait', title: 'Processes: fork, exec, wait', level: B, icon: '🌱', mins: 45,
    blurb: 'How every process on Linux is born: fork copies, exec replaces, wait reaps, and zombies happen in between.',
    cover: ['fork() returns twice', 'exec() replaces the program', 'wait() and exit status', 'Zombies and orphans', 'How a shell runs a command'] },
  { n: 4, slug: '04-process-states-pcb', title: 'Process States & the Process Control Block', level: B, icon: '🗂️', mins: 35,
    blurb: 'Running, ready, blocked: the state machine every process walks, and the kernel structure that tracks it.',
    cover: ['The five-state model', 'What the PCB / task_struct holds', 'Run queues and wait queues', '/proc/<pid>/status'] },
  { n: 5, slug: '05-threads', title: 'Threads', level: B, icon: '🧵', mins: 45,
    blurb: 'Several flows of control in one address space: pthreads, what threads share, and threads vs processes.',
    cover: ['What threads share and what they don\'t', 'pthread_create and join', 'Kernel threads vs user threads', 'Threads vs processes: a comparison', 'When to use each'] },
  { n: 6, slug: '06-context-switches-interrupts', title: 'Context Switches & Interrupts', level: B, icon: '🔄', mins: 40,
    blurb: 'Timer interrupts, saving and restoring registers, and why a context switch costs microseconds.',
    cover: ['Hardware interrupts and the timer', 'Saving and restoring context', 'Process vs thread switch cost', 'Measuring switches with vmstat', 'Top halves and bottom halves'] },
  { n: 7, slug: '07-scheduling-basics', title: 'CPU Scheduling I: FCFS, SJF, Round Robin', level: B, icon: '⏱️', mins: 50,
    blurb: 'Turnaround, waiting and response time, and how the classic policies trade them off. With a scheduler simulator.',
    cover: ['Metrics: turnaround, waiting, response', 'FCFS and the convoy effect', 'SJF and SRTF', 'Round robin and the quantum', 'Gantt charts'] },
  { n: 8, slug: '08-scheduling-mlfq-cfs', title: 'CPU Scheduling II: Priorities, MLFQ & Linux CFS', level: B, icon: '🎚️', mins: 50,
    blurb: 'Priorities and starvation, the multi-level feedback queue, and how Linux\'s CFS shares the CPU fairly.',
    cover: ['Priority scheduling and aging', 'MLFQ rules', 'CFS: virtual runtime and the red-black tree', 'nice values', 'EEVDF in newer kernels'] },
  { n: 9, slug: '09-ipc-pipes-signals-shm', title: 'IPC: Pipes, Signals & Shared Memory', level: B, icon: '📨', mins: 45,
    blurb: 'How processes talk: pipes and FIFOs, signals, shared memory and Unix sockets, and when to pick each.',
    cover: ['Pipes and FIFOs', 'Signals and handlers', 'Shared memory with mmap', 'Unix domain sockets', 'Choosing an IPC mechanism'] },
  { n: 10, slug: '10-file-descriptors', title: 'File Descriptors & "Everything Is a File"', level: B, icon: '🗃️', mins: 40,
    blurb: 'The fd table, open file descriptions and inodes; dup2, redirection, and why sockets are files too.',
    cover: ['The three tables: fd, open file, inode', 'open, read, write, close', 'dup2 and redirection', 'fds across fork and exec', 'ulimit -n and fd leaks'] },

  // ---------- Intermediate ----------
  { n: 11, slug: '11-address-spaces', title: 'Address Spaces & Virtual Memory', level: I, icon: '🗺️', mins: 45,
    blurb: 'Every process sees its own private memory: the address-space layout, and why virtual addresses exist.',
    cover: ['Code, heap, stack and mappings', 'Virtual vs physical addresses', 'Base and bounds, segmentation', '/proc/<pid>/maps'] },
  { n: 12, slug: '12-paging-page-tables', title: 'Paging & Page Tables', level: I, icon: '📄', mins: 50,
    blurb: 'Pages and frames, translating an address step by step, and multi-level page tables on x86-64.',
    cover: ['Pages, frames and offsets', 'Page table entries and flags', 'Translating an address by hand', 'Four-level page tables', 'Huge pages'] },
  { n: 13, slug: '13-tlb', title: 'The TLB', level: I, icon: '⚡', mins: 40,
    blurb: 'The cache that makes paging fast: hits and misses, TLB reach, flushes on context switch, and PCIDs.',
    cover: ['Why translation needs a cache', 'Hit rate and effective access time', 'TLB reach and huge pages', 'Flushes, ASIDs and PCIDs', 'TLB shootdowns'] },
  { n: 14, slug: '14-page-faults-demand-paging', title: 'Page Faults & Demand Paging', level: I, icon: '📥', mins: 45,
    blurb: 'Minor and major faults, lazy allocation, swap, and what the kernel does between the fault and the retry.',
    cover: ['Minor vs major faults', 'Demand paging and lazy allocation', 'Swap and the swap cache', 'Overcommit', 'Thrashing'] },
  { n: 15, slug: '15-page-replacement', title: 'Page Replacement: FIFO, LRU & Clock', level: I, icon: '♻️', mins: 50,
    blurb: 'Which page to evict: FIFO and Belady\'s anomaly, LRU, the clock algorithm, and Linux\'s active/inactive lists.',
    cover: ['Optimal (Belady) as a yardstick', 'FIFO and Belady\'s anomaly', 'LRU and why it\'s costly', 'Clock / second chance', 'Working sets'] },
  { n: 16, slug: '16-heap-malloc', title: 'The Heap: How malloc Works', level: I, icon: '🧰', mins: 45,
    blurb: 'brk and mmap, free lists, fragmentation, size classes, and why jemalloc and tcmalloc exist.',
    cover: ['brk/sbrk and mmap', 'Free lists and first/best fit', 'Fragmentation', 'Size classes and per-thread caches', 'Heap bugs: double free, overflow'] },
  { n: 17, slug: '17-race-conditions', title: 'Race Conditions & Critical Sections', level: I, icon: '🏁', mins: 45,
    blurb: 'Why counter++ loses updates, what a critical section is, and the requirements any fix must meet.',
    cover: ['counter++ is three instructions', 'Interleavings', 'Critical sections', 'Mutual exclusion, progress, bounded waiting', 'Data races vs race conditions'] },
  { n: 18, slug: '18-mutexes-spinlocks', title: 'Mutexes & Spinlocks', level: I, icon: '🔒', mins: 50,
    blurb: 'Test-and-set, spinning vs sleeping, futexes, and how pthread_mutex really works.',
    cover: ['Atomic test-and-set and compare-and-swap', 'Spinlocks', 'Sleeping locks and futexes', 'Lock contention and granularity', 'Reader–writer locks'] },
  { n: 19, slug: '19-condition-variables', title: 'Condition Variables', level: I, icon: '🔔', mins: 45,
    blurb: 'Waiting for a condition without spinning: wait/signal/broadcast, spurious wakeups and the while loop.',
    cover: ['Why a mutex alone isn\'t enough', 'wait, signal, broadcast', 'Always wait in a while loop', 'Lost wakeups', 'Mesa vs Hoare semantics'] },
  { n: 20, slug: '20-semaphores', title: 'Semaphores', level: I, icon: '🚦', mins: 40,
    blurb: 'Counting and binary semaphores, bounding concurrent access, and semaphores vs mutex + condition variable.',
    cover: ['P and V (wait and post)', 'Binary vs counting', 'Bounding access to a resource', 'Ordering with semaphores', 'Semaphores vs condition variables'] },
  { n: 21, slug: '21-classic-sync-problems', title: 'Classic Problems: Producer–Consumer, Readers–Writers, Dining Philosophers', level: I, icon: '🍝', mins: 55,
    blurb: 'The three problems every OS course and interview uses, solved correctly, with their traps.',
    cover: ['Bounded buffer', 'Readers–writers and writer starvation', 'Dining philosophers', 'Solutions that deadlock and ones that don\'t'] },
  { n: 22, slug: '22-deadlock', title: 'Deadlock: Conditions, Detection & Prevention', level: I, icon: '🪢', mins: 50,
    blurb: 'The four Coffman conditions, resource-allocation graphs, lock ordering, and the banker\'s algorithm.',
    cover: ['The four conditions', 'Resource-allocation and wait-for graphs', 'Prevention: lock ordering, trylock', 'Avoidance: the banker\'s algorithm', 'Detection and recovery', 'Livelock'] },
  { n: 23, slug: '23-file-systems', title: 'File Systems: Inodes, Directories & Blocks', level: I, icon: '🗄️', mins: 50,
    blurb: 'How a file becomes blocks on disk: inodes, directory entries, block allocation, links and the VFS.',
    cover: ['Inodes and data blocks', 'Directories are files', 'Hard vs symbolic links', 'Block allocation and extents', 'The VFS layer'] },
  { n: 24, slug: '24-journaling-crash-consistency', title: 'Journaling & Crash Consistency', level: I, icon: '📓', mins: 45,
    blurb: 'What a power cut does mid-write, fsck, write-ahead journaling, and copy-on-write file systems.',
    cover: ['The crash consistency problem', 'fsck', 'Data vs metadata journaling', 'ext4 journal modes', 'Copy-on-write: btrfs, ZFS'] },

  // ---------- Advanced ----------
  { n: 25, slug: '25-atomics-memory-models', title: 'Atomics & Memory Models', level: A, icon: '⚛️', mins: 55,
    blurb: 'Why CPUs and compilers reorder memory operations, and how C11 atomics and memory orders tame them.',
    cover: ['Reordering by compilers and CPUs', 'Store buffers', 'C11 atomics', 'Acquire, release and seq_cst', 'Memory barriers'] },
  { n: 26, slug: '26-lock-free', title: 'Lock-Free Data Structures (CAS, ABA)', level: A, icon: '🔓', mins: 55,
    blurb: 'Compare-and-swap loops, a lock-free stack, the ABA problem, and safe memory reclamation.',
    cover: ['CAS retry loops', 'A lock-free stack', 'The ABA problem and tagged pointers', 'Hazard pointers and RCU', 'Lock-free vs wait-free'] },
  { n: 27, slug: '27-thread-pools', title: 'Thread Pools & Work Stealing', level: A, icon: '🏊', mins: 45,
    blurb: 'Reusing threads, sizing pools for CPU vs I/O work, and work-stealing deques.',
    cover: ['Why pools', 'Sizing: cores and wait/compute', 'Work queues and backpressure', 'Work-stealing deques', 'Pools in Go, Java and Rust runtimes'] },
  { n: 28, slug: '28-io-multiplexing-epoll', title: 'I/O Multiplexing: select, poll, epoll', level: A, icon: '📡', mins: 50,
    blurb: 'Blocking vs non-blocking I/O, and how one thread watches thousands of sockets with epoll.',
    cover: ['Blocking vs non-blocking fds', 'select and poll and their O(n) cost', 'epoll: interest list and ready list', 'Level vs edge triggered', 'The C10K problem'] },
  { n: 29, slug: '29-event-loops-io-uring', title: 'Event Loops & io_uring', level: A, icon: '🌀', mins: 50,
    blurb: 'The reactor pattern behind Node and nginx, callbacks vs async/await, and io_uring\'s shared rings.',
    cover: ['The reactor loop', 'Callbacks, futures and async/await', 'Don\'t block the loop', 'io_uring submission and completion rings', 'Proactor vs reactor'] },
  { n: 30, slug: '30-mmap-copy-on-write', title: 'mmap & Copy-on-Write', level: A, icon: '🪞', mins: 45,
    blurb: 'Mapping files into memory, shared vs private mappings, and how fork() copies only what\'s written.',
    cover: ['mmap a file', 'MAP_SHARED vs MAP_PRIVATE', 'Copy-on-write after fork', 'Anonymous mappings', 'When mmap beats read()'] },
  { n: 31, slug: '31-page-cache-fsync', title: 'The Page Cache & fsync', level: A, icon: '💾', mins: 45,
    blurb: 'Why write() returns before the disk has the data, dirty pages and writeback, and fsync\'s real guarantees.',
    cover: ['The page cache', 'Dirty pages and writeback', 'fsync, fdatasync and O_DIRECT', 'fsync failures (fsyncgate)', 'Durability in databases'] },
  { n: 32, slug: '32-multicore-caches-numa', title: 'Multicore: Cache Coherence, False Sharing & NUMA', level: A, icon: '🧠', mins: 50,
    blurb: 'MESI, cache-line ping-pong, false sharing, CPU affinity and NUMA-aware memory.',
    cover: ['Private caches, shared memory', 'The MESI protocol', 'False sharing and padding', 'CPU affinity', 'NUMA nodes and local memory'] },
  { n: 33, slug: '33-virtualization', title: 'Virtualization & Hypervisors', level: A, icon: '🖥️', mins: 45,
    blurb: 'Type 1 vs type 2 hypervisors, trap-and-emulate, hardware virtualization and nested page tables.',
    cover: ['What a VM is', 'Type 1 vs type 2', 'Trap-and-emulate and VT-x', 'Nested page tables (EPT)', 'Paravirtualization and virtio'] },
  { n: 34, slug: '34-containers-namespaces-cgroups', title: 'Containers: Namespaces & cgroups', level: A, icon: '📦', mins: 50,
    blurb: 'A container is a process with a restricted view (namespaces) and a budget (cgroups). Build one by hand.',
    cover: ['PID, mount, network and user namespaces', 'cgroups v2: CPU and memory limits', 'Union file systems', 'Containers vs VMs', 'unshare in practice'] },
  { n: 35, slug: '35-booting-modules-drivers', title: 'Booting, Kernel Modules & Drivers', level: A, icon: '🥾', mins: 40,
    blurb: 'Firmware to init: the boot sequence, loadable kernel modules, and how a device driver plugs in.',
    cover: ['UEFI, bootloader, kernel, init/systemd', 'Kernel modules', 'Character and block devices', 'Interrupts and DMA', 'eBPF: safe kernel extensions'] },
  { n: 36, slug: '36-os-security', title: 'OS Security: Privileges, ASLR & Sandboxing', level: A, icon: '🔐', mins: 45,
    blurb: 'Users and capabilities, setuid, ASLR and NX, and sandboxing with seccomp.',
    cover: ['Users, groups and capabilities', 'setuid and privilege escalation', 'ASLR, NX and stack canaries', 'seccomp filters', 'Least privilege'] },

  // ---------- Expert ----------
  { n: 37, slug: '37-performance-tools', title: 'Performance Tools: perf, strace & /proc', level: E, icon: '🔬', mins: 45,
    blurb: 'Finding where the time goes: USE method, top/vmstat/iostat, strace, perf and flame graphs.',
    cover: ['The USE method', 'top, vmstat, iostat', 'strace and ltrace', 'perf and flame graphs', 'Off-CPU analysis'] },
  { n: 38, slug: '38-tail-latency', title: 'Tail Latency & the OS', level: E, icon: '📈', mins: 45,
    blurb: 'Why p99 is slow: scheduling delays, page faults, GC pauses, noisy neighbours, and what to do about them.',
    cover: ['Percentiles and fan-out', 'Run-queue delay', 'Page faults and THP compaction', 'CPU throttling under cgroups', 'Mitigations: pinning, hedging'] },
  { n: 39, slug: '39-priority-inversion-realtime', title: 'Priority Inversion & Real-Time Scheduling', level: E, icon: '🚀', mins: 40,
    blurb: 'The Mars Pathfinder bug, priority inheritance, and real-time scheduling classes.',
    cover: ['Priority inversion', 'The Mars Pathfinder resets', 'Priority inheritance and ceiling', 'SCHED_FIFO, SCHED_RR, SCHED_DEADLINE', 'PREEMPT_RT'] },
  { n: 40, slug: '40-os-interview-playbook', title: 'OS Interview Playbook', level: E, icon: '🎤', mins: 40,
    blurb: 'The questions that come up, how to structure answers, and the classic traps, drilled.',
    cover: ['Question map by topic', 'Process vs thread, done well', 'Explaining virtual memory in two minutes', 'Deadlock and synchronization questions', 'Trick questions'] },

  // ---------- Case studies ----------
  { n: 41, slug: '41-case-shell-pipeline', title: 'Case Study: How the Shell Runs ls | grep', level: CS, icon: '🐚', mins: 45,
    blurb: 'Parsing, pipe(), two forks, dup2, exec and wait: a pipeline traced syscall by syscall.',
    cover: ['Parsing the command line', 'pipe() and two forks', 'dup2 in each child', 'exec, and closing the right fds', 'wait and job control'] },
  { n: 42, slug: '42-case-nginx-connections', title: 'Case Study: How nginx Handles 10,000 Connections', level: CS, icon: '🌐', mins: 45,
    blurb: 'Master and worker processes, one epoll loop per core, non-blocking sockets and sendfile.',
    cover: ['Master and workers', 'An event loop per worker', 'accept and the thundering herd', 'sendfile and zero-copy', 'Compared with thread-per-connection'] },
  { n: 43, slug: '43-case-postgres-on-os', title: 'Case Study: How PostgreSQL Relies on the OS', level: CS, icon: '🐘', mins: 45,
    blurb: 'Process-per-connection, shared buffers in shared memory, the double buffering with the page cache, and fsync.',
    cover: ['Process per connection', 'Shared buffers and the page cache', 'WAL and fsync', 'The 2018 fsync bug', 'Huge pages and OOM tuning'] },
  { n: 44, slug: '44-case-redis-fork', title: 'Case Study: Redis — One Thread and fork() Snapshots', level: CS, icon: '🟥', mins: 40,
    blurb: 'A single-threaded event loop, and RDB snapshots that rely on copy-on-write after fork.',
    cover: ['Why one thread is enough', 'The event loop', 'BGSAVE: fork and copy-on-write', 'Memory spikes and overcommit', 'I/O threads in Redis 6+'] },
  { n: 45, slug: '45-case-goroutines-jvm-threads', title: 'Case Study: Goroutines vs JVM Threads (M:N Scheduling)', level: CS, icon: '🐹', mins: 45,
    blurb: 'Go\'s G-M-P scheduler, Java\'s platform and virtual threads, and what M:N scheduling buys.',
    cover: ['1:1 vs M:N threading', 'Go: G, M and P', 'Work stealing and syscalls', 'Java virtual threads and pinning', 'Choosing'] },
  { n: 46, slug: '46-case-docker-run', title: 'Case Study: What docker run Really Does', level: CS, icon: '🐳', mins: 45,
    blurb: 'From the CLI to containerd and runc: image layers, namespaces, cgroups, and PID 1.',
    cover: ['CLI, daemon, containerd, runc', 'Image layers and overlayfs', 'clone() with namespaces', 'cgroup limits', 'PID 1 and signals'] },
  { n: 47, slug: '47-case-chrome-sandbox', title: 'Case Study: Chrome\'s Multi-Process Sandbox', level: CS, icon: '🧪', mins: 40,
    blurb: 'Browser, renderer and GPU processes, site isolation, IPC, and seccomp-based sandboxing.',
    cover: ['Why multiple processes', 'Site isolation', 'IPC between processes', 'The Linux sandbox: namespaces + seccomp', 'Memory cost trade-offs'] },
  { n: 48, slug: '48-case-oom-killer', title: 'Case Study: An OOM-Killer Incident', level: CS, icon: '💥', mins: 40,
    blurb: 'A service killed at 3 a.m.: overcommit, the OOM killer\'s choice, cgroup limits, and the postmortem.',
    cover: ['The symptoms', 'Overcommit and RSS', 'How the OOM killer picks a victim', 'cgroup memory limits in containers', 'Fixes and prevention'] },
];
