// Installs the shared visual components (sequence diagrams, workflows, comparison tables,
// use-case callouts) into each course's runtime and stylesheet. Idempotent: re-run it after
// editing tools/components/visuals.{js,css} and the marked blocks are replaced in place.
//   node tools/components/install.cjs
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..', '..');
const js = fs.readFileSync(path.join(__dirname, 'visuals.js'), 'utf8');
const css = fs.readFileSync(path.join(__dirname, 'visuals.css'), 'utf8');
const COURSES = { 'system-design': 'SD', 'ml-ai-systems': 'ML', dsa: 'DSA', lld: 'LLD' };
const B = '/* >>> shared visuals (generated by tools/components/install.cjs) */';
const E = '/* <<< shared visuals */';

function put(src, block, anchor) {
  const i = src.indexOf(B);
  if (i >= 0) {
    const j = src.indexOf(E, i);
    return src.slice(0, i) + block + src.slice(j + E.length);
  }
  const k = src.indexOf(anchor);
  if (k < 0) throw new Error('anchor not found: ' + anchor);
  return src.slice(0, k) + block + '\n\n' + src.slice(k);
}

for (const [dir, ns] of Object.entries(COURSES)) {
  const appPath = path.join(root, dir, 'assets', 'app.js');
  let app = fs.readFileSync(appPath, 'utf8');
  const initLine = `  ${ns}.initComponents = function (root) {`;
  app = put(app, `${B}\n${js.replace(/__NS__/g, ns).trimEnd()}\n  ${E}`, initLine);
  const lineRe = new RegExp(`(  ${ns}\\.initComponents = function \\(root\\) \\{)([^\\n]*)(\\};)`);
  app = app.replace(lineRe, (m, a, body, c) => a + (body.includes('initSeq') ? body : body.replace(/ $/, ' initSeq(root); initFlow(root); ')) + c);
  fs.writeFileSync(appPath, app);

  const cssPath = path.join(root, dir, 'assets', 'style.css');
  let st = fs.readFileSync(cssPath, 'utf8');
  const i = st.indexOf(B);
  const block = `${B}\n${css.trimEnd()}\n${E}`;
  st = i >= 0 ? st.slice(0, i) + block + st.slice(st.indexOf(E, i) + E.length) : st.trimEnd() + '\n\n' + block + '\n';
  fs.writeFileSync(cssPath, st);
  console.log('installed into', dir);
}
